accuracy: true
batch_size: 20
cache_dir: /mnt/cache/ag_news/std/kronfluence
data_root: /mnt/dataset/
dataset_name: ag_news
dataset_type: std
device: cuda
features_dir: /mnt/cache/ag_news/std/features
grad_dir: /mnt/cache/ag_news/std/tracin/best
hf_id: MoritzWeckbecker/Llama-3.2-1B_ag-news-0
model_path: /mnt/checkpoints/ag_news/std/ag_news_None_best
num_batches_per_file: 1
num_files: 1
save_dir: /mnt/outputs/
start_file: 93
validation_size: 2000
xai_method: kronfluence
