batch_size: 16
cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/std/arnoldi
data_root: /home/fe/yolcu/Documents/Code/DualView-wip/../Datasets
dataset_name: MNIST
dataset_type: std
device: cpu
features_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/std/features
grad_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/std/tracin/best
metric: std
model_name: basic_conv
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/MNIST/std/MNIST_basic_conv_best
num_classes: 10
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/test_output
validation_size: 2000
xpl_roots: [
  "/home/fe/yolcu/Documents/Code/DualView-wip/explanations/MNIST/std/dualview_0.1/",
  "/home/fe/yolcu/Documents/Code/DualView-wip/explanations/MNIST/std/dualview_0.01/",
  "/home/fe/yolcu/Documents/Code/DualView-wip/explanations/MNIST/std/dualview_0.001/",
  "/home/fe/yolcu/Documents/Code/DualView-wip/explanations/MNIST/std/dualview_0.0001/",
  "/home/fe/yolcu/Documents/Code/DualView-wip/explanations/MNIST/std/lissa/",
  "/home/fe/yolcu/Documents/Code/DualView-wip/explanations/MNIST/std/arnoldi/",
  "/home/fe/yolcu/Documents/Code/DualView-wip/explanations/MNIST/std/representer/",
  "/home/fe/yolcu/Documents/Code/DualView-wip/explanations/MNIST/std/tracin/",
  "/home/fe/yolcu/Documents/Code/DualView-wip/explanations/MNIST/std/gradcos/",
  "/home/fe/yolcu/Documents/Code/DualView-wip/explanations/MNIST/std/graddot/",
  ]
method_names: ["dualview_0.1", "dualview_0.01", "dualview_0.001", "dualview_0.0001", "lissa", "arnoldi", "representer", "tracin", "gradcos", "graddot"]

