augmentation: crop_flip
base_epoch: 0
batch_size: 64
data_root: /mnt/dataset/
dataset_name: AWA
dataset_type: std
device: cuda
epochs: 200
loss: cross_entropy
lr: 0.001
model_name: resnet50
momentum: 0
num_batches_eval: 200
num_classes: 50
optimizer: sgd
save_dir: /mnt/outputs/
save_each: 10
scheduler: constant
validation_size: 2000
weight_decay: 0
