augmentation: crop_rotate
base_epoch: 0
batch_size: 64
data_root: /mnt/dataset/
dataset_name: AWA
dataset_type: std
device: cuda
epochs: 100
loss: cross_entropy
lr: 0.5
model_name: resnet50
model_path: /mnt/checkpoints/AWA/std/resnet50_std/resnet50_imagenet1k_v1.pth
momentum: 0
num_batches_eval: 200
num_classes: 50
optimizer: sgd
save_dir: /mnt/outputs/
save_each: 5
scheduler: constant
validation_size: 2000
weight_decay: 1.0e-05
