augmentation: crop
base_epoch: 0
batch_size: 64
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
- - 10
  - 11
- - 12
  - 13
- - 14
  - 15
- - 16
  - 17
- - 18
  - 19
- - 20
  - 21
- - 22
  - 23
- - 24
  - 25
- - 26
  - 27
- - 28
  - 29
- - 30
  - 31
- - 32
  - 33
- - 34
  - 35
- - 36
  - 37
- - 38
  - 39
- - 40
  - 41
- - 42
  - 43
- - 44
  - 45
- - 46
  - 47
- - 48
  - 49
data_root: /home/yolcu/Documents/Code/DualXDA/src/datasets
dataset_name: AWA
dataset_type: group
device: cpu
epochs: 10
loss: cross_entropy
lr: 0.01
model_name: resnet50
model_path: <model_path>
momentum: 0.9
num_batches_eval: 200
num_classes: 50
optimizer: sgd
save_dir: /home/yolcu/Documents/Code/DualXDA/checkpoints/AWA/group/resnet50_group
save_each: 2
scheduler: annealing
validation_size: 2000
weight_decay: 1.0e-05
