batch_size: 16
cache_dir: c:\Users\weckbecker\DualView-wip/cache/MNIST/group/influence
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: c:\Users\weckbecker\DualView-wip/src/datasets
dataset_name: MNIST
dataset_type: group
device: cpu
features_dir: c:\Users\weckbecker\DualView-wip/cache/MNIST/group/features
grad_dir: c:\Users\weckbecker\DualView-wip/cache/MNIST/group/tracin/best
metric: groupk
model_name: basic_conv
num_classes: 10
save_dir: c:\Users\weckbecker\DualView-wip/test_output
validation_size: 2000
xai_method: influence
xpl_root: c:\Users\weckbecker\DualView-wip/explanations/MNIST/group/influence/
