batch_size: 16
cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/group/feature_similarity_cos
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: ~/Documents/Code/Datasets
dataset_name: MNIST
dataset_type: group
device: cpu
features_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/group/features
grad_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/group/tracin/best
lds_cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/group
metric: group
model_name: basic_conv
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/MNIST/group/MNIST_basic_conv_best
num_classes: 10
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/test_output
validation_size: 2000
xai_method: feature_similarity_cos
xpl_root: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/MNIST/group/feature_similarity_cos/
