batch_size: 16
cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/corrupt/feature_similarity_cos
data_root: ~/Documents/Code/Datasets
dataset_name: MNIST
dataset_type: corrupt
device: cpu
features_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/corrupt/features
grad_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/corrupt/tracin/best
lds_cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/corrupt
metric: corrupt
model_name: basic_conv
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/MNIST/corrupt/MNIST_basic_conv_best
num_classes: 10
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/test_output
validation_size: 2000
xai_method: feature_similarity_cos
xpl_root: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/MNIST/std/feature_similarity_cos/
