C: 0.001
batch_size: 16
cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/mark/dualview_0.001
data_root: ~/Documents/Code/Datasets
dataset_name: MNIST
dataset_type: mark
device: cpu
features_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/mark/features
grad_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/mark/tracin/best
lds_cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/mark
metric: mark
model_name: basic_conv
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/MNIST/mark/MNIST_basic_conv_best
num_classes: 10
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/test_output
validation_size: 2000
xai_method: dualview
xpl_root: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/MNIST/mark/dualview_0.001/
