C: 0.01
augmentation: crop
batch_size: 16
cache_dir: c:\Users\weckbecker\DualView-wip/cache/MNIST/std/dualview_0.01
data_root: c:\Users\weckbecker\DualView-wip/src/datasets
dataset_name: MNIST
dataset_type: std
device: cpu
epochs: 200
features_dir: c:\Users\weckbecker\DualView-wip/cache/MNIST/std/features
grad_dir: c:\Users\weckbecker\DualView-wip/cache/MNIST/std/tracin/best
loss: cross_entropy
lr: 0.005
metric: leave_out
model_name: basic_conv
momentum: 0.9
num_classes: 10
optimizer: sgd
save_dir: c:\Users\weckbecker\DualView-wip/test_output
scheduler: constant
validation_size: 2000
weight_decay: 0
xai_method: dualview
xpl_root: c:\Users\weckbecker\DualView-wip/explanations/MNIST/std/dualview/
