batch_size: 16
cache_dir: c:\Users\weckbecker\DualView-wip/cache/MNIST/mark/trak
data_root: c:\Users\weckbecker\DualView-wip/src/datasets
dataset_name: MNIST
dataset_type: mark
device: cpu
features_dir: c:\Users\weckbecker\DualView-wip/cache/MNIST/mark/features
grad_dir: c:\Users\weckbecker\DualView-wip/cache/MNIST/mark/tracin/best
metric: mark
model_name: basic_conv
model_path: c:\Users\weckbecker\DualView-wip/checkpoints/MNIST/mark/basic_conv_mark/MNIST_basic_conv_best
num_classes: 10
save_dir: c:\Users\weckbecker\DualView-wip/test_output
validation_size: 2000
xai_method: trak
xpl_root: c:\Users\weckbecker\DualView-wip/explanations/MNIST/mark/trak/
