C: 0.1
augmentation: flip
batch_size: 16
data_root: c:\Users\weckbecker\DualView-wip/src/datasets
dataset_name: MNIST
device: cpu
epochs: 100
loss: cross_entropy
lr: 0.01
metric: lds
model_name: basic_conv
momentum: 0
num_classes: 10
optimizer: sgd
save_dir: c:\Users\weckbecker\DualView-wip/test_output
scheduler: constant
validation_size: 2000
weight_decay: 0
xai_method: dualview
xpl_root: c:\Users\weckbecker\DualView-wip/explanations/MNIST/std/basic_conv_std/dualview_0.1
