C: 0.1
augmentation: crop
batch_size: 8
cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/std/dualview_0.1
data_root: ~/Documents/Code/Datasets
dataset_name: MNIST
dataset_type: std
device: cpu
epochs: 200
features_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/std/features
grad_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/std/tracin/best
lds_cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/only_batch
loss: cross_entropy
lr: 0.0016666666666666668
metric: only_batch
model_name: basic_conv
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/MNIST/std/MNIST_basic_conv_best
momentum: 0.9
num_classes: 10
optimizer: sgd
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/test_output
scheduler: constant
validation_size: 2000
weight_decay: 0
xai_method: dualview
xpl_root: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/MNIST/std/dualview_0.1/
