batch_size: 128
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: c:\Users\weckbecker\DualView-wip/src/datasets
dataset_name: MNIST
device: cpu
metric: group
model_name: basic_conv
num_classes: 10
save_dir: c:\Users\weckbecker\DualView-wip/test_output
validation_size: 2000
xai_method: representer
xpl_root: c:\Users\weckbecker\DualView-wip/explanations/MNIST/group/basic_conv_group/representer
