accuracy: true
batch_size: 20
cache_dir: /mnt/cache/AWA/corrupt/trak
data_root: /mnt/dataset/
dataset_name: AWA
dataset_type: corrupt
device: cuda
features_dir: /mnt/cache/AWA/corrupt/features
grad_dir: /mnt/cache/AWA/corrupt/tracin/best
model_name: resnet50
model_path: /mnt/checkpoints/AWA/corrupt/AWA_resnet50_best
num_batches_per_file: 1
num_classes: 50
num_files: 1
save_dir: /mnt/outputs/
start_file: 2
validation_size: 2000
xai_method: trak
