accuracy: true
batch_size: 20
cache_dir: /mnt/cache/AWA/std/representer
data_root: /mnt/dataset/
dataset_name: AWA
dataset_type: std
device: cuda
features_dir: /mnt/cache/AWA/std/features
grad_dir: /mnt/cache/AWA/std/tracin/best
model_name: resnet50
model_path: /mnt/checkpoints/AWA/std/AWA_resnet50_best
num_batches_per_file: 1
num_classes: 50
num_files: 1
save_dir: /mnt/outputs/
start_file: 4
validation_size: 2000
xai_method: representer
