accuracy: true
batch_size: 20
cache_dir: /mnt/cache/AWA/switched/tracin
data_root: /mnt/dataset/
dataset_name: AWA
dataset_type: switched
device: cuda
features_dir: /mnt/cache/AWA/switched/features
grad_dir: /mnt/cache/AWA/switched/tracin/best
model_name: resnet50
model_path: /mnt/checkpoints/AWA/switched/AWA_resnet50
num_batches_per_file: 1
num_classes: 50
num_files: 1
save_dir: /mnt/outputs/
start_file: 21
validation_size: 2000
xai_method: tracin
