accuracy: true
batch_size: 20
cache_dir: /mnt/cache/AWA/group/trak
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
- - 10
  - 11
- - 12
  - 13
- - 14
  - 15
- - 16
  - 17
- - 18
  - 19
- - 20
  - 21
- - 22
  - 23
- - 24
  - 25
- - 26
  - 27
- - 28
  - 29
- - 30
  - 31
- - 32
  - 33
- - 34
  - 35
- - 36
  - 37
- - 38
  - 39
- - 40
  - 41
- - 42
  - 43
- - 44
  - 45
- - 46
  - 47
- - 48
  - 49
data_root: /mnt/dataset/
dataset_name: AWA
dataset_type: group
device: cuda
features_dir: /mnt/cache/AWA/group/features
grad_dir: /mnt/cache/AWA/group/tracin/best
model_name: resnet50
model_path: /mnt/checkpoints/AWA/group/AWA_resnet50_best
num_batches_per_file: 1
num_classes: 50
num_files: 1
save_dir: /mnt/outputs/
start_file: 49
validation_size: 2000
xai_method: trak
