accuracy: true
batch_size: 16
data_root: /mnt/dataset/
dataset_name: AWA
dataset_type: mark
device: cuda
model_name: resnet50
model_path: /mnt/checkpoints/AWA/mark/resnet50_mark/AWA_resnet50
num_batches_per_file: 1
num_classes: 50
num_files: 100
save_dir: /mnt/outputs/
skip: 2230
start_file: 0
validation_size: 2000
xai_method: tracin
