accuracy: true
batch_size: 16
data_root: /mnt/dataset/
dataset_name: AWA
dataset_type: switched_one_file
device: cuda
model_name: resnet50
model_path: /mnt/checkpoints/AWA/switched_one_file/resnet50_switched_one_file/AWA_resnet50
num_batches_per_file: 1
num_classes: 50
num_files: 100
save_dir: c:\Users\weckbecker\DualView-wip/explanations/AWA/switched_one_file/resnet50_switched_one_file/graddot
skip: 2230
start_file: 0
validation_size: 2000
xai_method: graddot
