base_epoch: 0
batch_size: 64
data_root: /mnt/dataset/
dataset_name: Shapes2x2
dataset_type: std
device: cuda
epochs: 30
loss: cross_entropy
lr: 0.0001
model_name: resnet50
momentum: 0.9
num_batches_eval: 200
num_classes: 2
optimizer: sgd
save_dir: /mnt/outputs/
save_each: 2
scheduler: constant
validation_size: 2000
weight_decay: 1.0e-05
