accuracy: true
batch_size: 32
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: /home/fe/yolcu/Documents/Code/Datasets
dataset_name: MNIST
dataset_type: std
device: cpu
model_name: basic_conv
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/MNIST/std/basic_conv_std/MNIST_basic_conv
num_batches_per_file: 100
num_classes: 10
num_files: 500
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/MNIST/std/basic_conv_std/trak
start_file: 0
validation_size: 2000
xai_method: trak
