C: 0.01
accuracy: true
batch_size: 200
cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/std/dualview_0.01
data_root: /home/fe/yolcu/Documents/Code/DualView-wip/../Datasets
dataset_name: MNIST
dataset_type: std
device: cpu
features_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/std/features
grad_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/std/tracin/best
model_name: basic_conv
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/MNIST/std/MNIST_basic_conv_best
num_batches_per_file: 1
num_classes: 10
num_files: 1
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/MNIST/std/dualview_0.01
start_file: 9
validation_size: 2000
xai_method: dualview
