accuracy: true
batch_size: 20
data_root: /home/fe/yolcu/Documents/Code/DualView-wip/src/datasets
dataset_name: MNIST
dataset_type: mark
device: cpu
model_name: basic_conv
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/MNIST/mark/MNIST_basic_conv
num_batches_per_file: 1
num_classes: 10
num_files: 1
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/MNIST/mark/graddot
start_file: 0
validation_size: 2000
xai_method: graddot
