C: 0.93
accuracy: true
batch_size: 200
cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/mark/representer_0.93
data_root: /home/fe/yolcu/Documents/Code/DualView-wip/../Datasets
dataset_name: MNIST
dataset_type: mark
device: cpu
features_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/mark/features
grad_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/mark/tracin/best
model_name: basic_conv
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/MNIST/mark/MNIST_basic_conv_best
num_batches_per_file: 1
num_classes: 10
num_files: 1
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/MNIST/mark/representer_0.93
start_file: 9
validation_size: 2000
xai_method: representer
