C: 1.0e-05
accuracy: true
batch_size: 200
cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/corrupt/dualview_1e-05
data_root: /home/fe/yolcu/Documents/Code/DualView-wip/src/datasets
dataset_name: MNIST
dataset_type: corrupt
device: cpu
features_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/corrupt/features
grad_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/corrupt/tracin/best
model_name: basic_conv
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/MNIST/corrupt/MNIST_basic_conv_best
num_batches_per_file: 1
num_classes: 10
num_files: 1
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/MNIST/corrupt/dualview_1e-05
start_file: 9
validation_size: 2000
xai_method: dualview
