C: 0.01
accuracy: true
batch_size: 200
cache_dir: c:\Users\weckbecker\DualView-wip/cache/MNIST/mark/dualview_0.01
data_root: c:\Users\weckbecker\DualView-wip/../Datasets
dataset_name: MNIST
dataset_type: mark
device: cpu
features_dir: c:\Users\weckbecker\DualView-wip/cache/MNIST/mark/features
grad_dir: c:\Users\weckbecker\DualView-wip/cache/MNIST/mark/tracin/best
model_name: basic_conv
model_path: c:\Users\weckbecker\DualView-wip/checkpoints/MNIST/mark/MNIST_basic_conv_best
num_batches_per_file: 1
num_classes: 10
num_files: 1
save_dir: c:\Users\weckbecker\DualView-wip/explanations/MNIST/mark/dualview_0.01
start_file: 9
validation_size: 2000
xai_method: dualview
