accuracy: true
batch_size: 16
data_root: /home/yolcu/Documents/Code/DualView_wip/src/datasets
dataset_name: MNIST
dataset_type: std
device: cpu
model_name: basic_conv
model_path: /home/yolcu/Documents/Code/DualView_wip/checkpoints/MNIST/std/MNIST_basic_conv_189
num_batches_per_file: 1
num_classes: 10
num_files: 1
save_dir: /home/yolcu/Documents/Code/DualView_wip/explanations/MNIST/std/basic_conv_std/gradcos
start_file: 0
validation_size: 2000
xai_method: gradcos
