accuracy: true
batch_size: 16
data_root: c:\Users\weckbecker\DualView-wip/src/datasets
dataset_name: MNIST
dataset_type: std
device: cpu
model_name: basic_conv
model_path: c:\Users\weckbecker\DualView-wip/checkpoints/MNIST/std/basic_conv_std/MNIST_basic_conv
num_batches_per_file: 1
num_classes: 10
num_files: 100
save_dir: c:\Users\weckbecker\DualView-wip/explanations/MNIST/std/basic_conv_std/trak
skip: 2230
start_file: 0
validation_size: 2000
xai_method: trak
