C: 1.0
accuracy: true
batch_size: 32
cache_dir: /mnt/cache/CIFAR/corrupt/dualview_1.0
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: /mnt/dataset
dataset_name: CIFAR
dataset_type: corrupt
device: cuda
features_dir: /mnt/cache/CIFAR/corrupt/features
grad_dir: /mnt/cache/CIFAR/corrupt/tracin/best
model_name: resnet18
model_path: /mnt/checkpoints/CIFAR/corrupt/CIFAR_resnet18_best
num_batches_per_file: 100
num_classes: 10
num_files: 500
save_dir_explainer: /mnt/outputs/CIFAR/corrupt/dualview_1.0_1.0
save_dir_results: /mnt/outputs/CIFAR/corrupt/dualview_1.0_1.0
start_file: 0
validation_size: 2000
xai_method: dualview
