C: 0.1
augmentation: flip
batch_size: 8
cache_dir: /home/yolcu/Documents/Code/DualXDA/cache/AWA/std/dualda_0.1
data_root: <data_root>
dataset_name: AWA
dataset_type: std
device: cpu
epochs: 30
features_dir: /home/yolcu/Documents/Code/DualXDA/cache/AWA/std/features
grad_dir: /home/yolcu/Documents/Code/DualXDA/cache/AWA/std/tracin/best
lds_cache_dir: /home/yolcu/Documents/Code/DualXDA/cache/AWA/lds
loss: cross_entropy
lr: 0.001
metric: lds
model_name: resnet50
model_path: /home/yolcu/Documents/Code/DualXDA/checkpoints/AWA/std/AWA_resnet50_best
momentum: 0.9
num_classes: 50
optimizer: sgd
save_dir: /home/yolcu/Documents/Code/DualXDA/test_output
scheduler: constant
validation_size: 2000
weight_decay: 0
xai_method: dualda
xpl_root: /home/yolcu/Documents/Code/DualXDA/explanations/AWA/std/dualda_0.1/
