C: 0.001
batch_size: 32
cache_dir: /home/yolcu/Documents/Code/DualXDA/cache/AWA/mark/dualda_0.001
data_root: <data_root>
dataset_name: AWA
dataset_type: mark
device: cpu
features_dir: /home/yolcu/Documents/Code/DualXDA/cache/AWA/mark/features
grad_dir: /home/yolcu/Documents/Code/DualXDA/cache/AWA/mark/tracin/best
lds_cache_dir: /home/yolcu/Documents/Code/DualXDA/cache/AWA/shortcut_detection
metric: shortcut_detection
model_name: resnet50
model_path: /home/yolcu/Documents/Code/DualXDA/checkpoints/AWA/mark/AWA_resnet50_best
num_classes: 50
save_dir: /home/yolcu/Documents/Code/DualXDA/test_output
validation_size: 2000
xai_method: dualda
xpl_root: /home/yolcu/Documents/Code/DualXDA/explanations/AWA/mark/dualda_0.001/
