C: 1.0e-05
batch_size: 32
cache_dir: /home/yolcu/Documents/Code/DualXDA/cache/AWA/corrupt/dualda_1e_05
data_root: <data_root>
dataset_name: AWA
dataset_type: corrupt
device: cpu
features_dir: /home/yolcu/Documents/Code/DualXDA/cache/AWA/corrupt/features
grad_dir: /home/yolcu/Documents/Code/DualXDA/cache/AWA/corrupt/tracin/best
lds_cache_dir: /home/yolcu/Documents/Code/DualXDA/cache/AWA/mislabeling_detection
metric: mislabeling_detection
model_name: resnet50
model_path: /home/yolcu/Documents/Code/DualXDA/checkpoints/AWA/corrupt/AWA_resnet50_best
num_classes: 50
save_dir: /home/yolcu/Documents/Code/DualXDA/test_output
validation_size: 2000
xai_method: dualda
xpl_root: /home/yolcu/Documents/Code/DualXDA/explanations/AWA/corrupt/dualda_1e_05/
