C: 0.001
batch_size: 32
cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/std/dualda_0.001
data_root: <data_root>
dataset_name: AWA
dataset_type: std
device: cpu
features_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/std/features
grad_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/std/tracin/best
lds_cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/data_pruning
metric: data_pruning
model_name: resnet50
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/AWA/std/AWA_resnet50_best
num_classes: 50
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/test_output
validation_size: 2000
xai_method: dualda
xpl_root: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/AWA/std/dualda_0.001/
