C: 0.1
accuracy: true
batch_size: 200
cache_dir: /home/yolcu/Documents/Code/DualXDA/cache/tweet_sentiment_extraction/std/dualda_0.1
data_root: /home/yolcu/Documents/Code/DualXDA/../Datasets
dataset_name: tweet_sentiment_extraction
dataset_type: std
device: cuda
features_dir: /home/yolcu/Documents/Code/DualXDA/cache/tweet_sentiment_extraction/std/features
grad_dir: /home/yolcu/Documents/Code/DualXDA/cache/tweet_sentiment_extraction/std/tracin/best
model_name: GPT2
model_path: /home/yolcu/Documents/Code/DualXDA/checkpoints/tweet_sentiment_extraction/std/tweet_sentiment_extraction_GPT2_best
num_batches_per_file: 1
num_classes: GPT2
num_files: 1
save_dir: /home/yolcu/Documents/Code/DualXDA/explanations/tweet_sentiment_extraction/std/dualda_0.1
start_file: 0
validation_size: 2000
xai_method: dualda
