C: 0.0000001
accuracy: true
batch_size: 200
cache_dir: ../cache/tweet_sentiment_extraction/std/dualda_0.1
data_root: ../../Datasets
dataset_name: tweet_sentiment_extraction
dataset_type: std
device: cuda
features_dir: ../cache/tweet_sentiment_extraction/std/features
grad_dir: ../cache/tweet_sentiment_extraction/std/tracin/best
model_name: GPT2
model_path: ../checkpoints/tweet_sentiment_extraction/std/tweet_sentiment_extraction_GPT2_best
num_batches_per_file: 1
num_classes: GPT2
num_files: 2
save_dir: ../explanations/tweet_sentiment_extraction/std/dualda_0.1
start_file: 0
validation_size: 2000
xai_method: dualda
hf_id: herrerovir/gpt2-tweet-sentiment-model
