C: 0.1
accuracy: true
batch_size: 200
cache_dir: /home/yolcu/Documents/Code/DualXDA/cache/MNIST/mark/dualda_0.1
data_root: <data_root>
dataset_name: MNIST
dataset_type: mark
device: cpu
features_dir: /home/yolcu/Documents/Code/DualXDA/cache/MNIST/mark/features
grad_dir: /home/yolcu/Documents/Code/DualXDA/cache/MNIST/mark/tracin/best
model_name: basic_conv
model_path: /home/yolcu/Documents/Code/DualXDA/checkpoints/MNIST/mark/MNIST_basic_conv_best
num_batches_per_file: 1
num_classes: 10
num_files: 1
save_dir: /home/yolcu/Documents/Code/DualXDA/explanations/MNIST/mark/dualda_0.1
start_file: 2
validation_size: 2000
xai_method: dualda
