C: 1.0e-05
accuracy: true
batch_size: 100
cache_dir: ../cache/ag_news/llama/dualda_1e-05_v4
data_root: ../../Datasets
dataset_name: ag_news
dataset_type: std
device: cuda
features_dir: ../cache/ag_news/llama/features_v4
grad_dir: ../cache/ag_news/std/tracin/best
hf_id: MoritzWeckbecker/Llama-3.2-1B_ag-news-4
model_path: ../checkpoints/ag_news/std/ag_news_None_best
num_batches_per_file: 1
num_files: 76
save_dir: ../explanations/ag_news/llama/dualda_1e-05_v4
start_file: 0
validation_size: 2000
xai_method: dualda
