accuracy: true
batch_size: 5
cache_dir: /home/yolcu/Documents/Code/DualXDA/cache/ag_news/std/lissa
data_root: /home/yolcu/Documents/Code/DualXDA/../Datasets
dataset_name: ag_news
dataset_type: std
device: cuda
features_dir: /home/yolcu/Documents/Code/DualXDA/cache/ag_news/std/features
grad_dir: /home/yolcu/Documents/Code/DualXDA/cache/ag_news/std/tracin/best
hf_id: MoritzWeckbecker/gpt2-large_ag-news_full-1
model_path: /home/yolcu/Documents/Code/DualXDA/checkpoints/ag_news/std/ag_news_None_best
num_batches_per_file: 1
num_files: 1
save_dir: /home/yolcu/Documents/Code/DualXDA/explanations/ag_news/std/lissa
start_file: 0
validation_size: 2000
xai_method: lissa
