accuracy: true
batch_size: 5
cache_dir: ../cache/ag_news/llama/lissa_v3
data_root: ../../Datasets
dataset_name: ag_news
dataset_type: std
device: cuda
features_dir: ../cache/ag_news/llama/features_v3
grad_dir: ../cache/ag_news/std/tracin/best
hf_id: MoritzWeckbecker/Llama-3.2-1B_ag-news-3
model_path: ../checkpoints/ag_news/std/ag_news_None_best
num_batches_per_file: 1
num_files: 1
save_dir: ../explanations/ag_news/llama/lissa_v3
start_file: 0
validation_size: 2000
xai_method: lissa
