C: 0.001
accuracy: true
batch_size: 200
cache_dir: ../cache/ag_news/std/dualda_0.001_v2
data_root: ../../Datasets
dataset_name: ag_news
dataset_type: std
device: cuda
features_dir: ../cache/ag_news/std/features_v2
grad_dir: ../cache/ag_news/std/tracin/best
hf_id: MoritzWeckbecker/Llama-3.2-1B_ag-news-0-2
model_path: ../checkpoints/ag_news/std/ag_news_None_best
num_batches_per_file: 1
num_files: 38
save_dir: ../explanations/ag_news/std/dualda_0.001_v2
start_file: 0
validation_size: 2000
xai_method: dualda
