augmentation: crop_flip_rotate
base_epoch: 0
batch_size: 64
data_root: /home/fe/yolcu/Documents/Code/DualView-wip/src/datasets
dataset_name: CIFAR
dataset_type: std
device: cpu
epochs: 2
loss: cross_entropy
lr: 0.005
model_name: resnet18
momentum: 0
num_batches_eval: 200
num_classes: 10
optimizer: rmsprop
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/CIFAR/std/resnet18_std
save_each: 1
scheduler: constant
validation_size: 2000
weight_decay: 0.0001
