augmentation: crop_rotate
base_epoch: 0
batch_size: 64
data_root: c:\Users\weckbecker\DualView-wip/src/datasets
dataset_name: CIFAR
dataset_type: std
device: cpu
epochs: 10
loss: cross_entropy
lr: 0.01
model_name: resnet18
momentum: 0
num_batches_eval: 200
num_classes: 10
optimizer: adam
save_dir: c:\Users\weckbecker\DualView-wip/checkpoints/CIFAR/std/resnet18_std
save_each: 2
scheduler: annealing
validation_size: 2000
weight_decay: 0
