C: 0.1
accuracy: true
batch_size: 200
cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/mark/dualview_0.1
data_root: <data_root>
dataset_name: AWA
dataset_type: mark
device: cpu
features_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/mark/features
grad_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/mark/tracin/best
model_name: resnet50
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/AWA/mark/AWA_resnet50_best
num_batches_per_file: 1
num_classes: 50
num_files: 1
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/AWA/mark/dualview_0.1
start_file: 2
validation_size: 2000
xai_method: dualview
