C: 1.0e-05
accuracy: true
batch_size: 200
cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/std/dualda_1e-05
data_root: <data_root>
dataset_name: AWA
dataset_type: std
device: cpu
features_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/std/features
grad_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/std/tracin/best
model_name: resnet50
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/AWA/std/AWA_resnet50_best
num_batches_per_file: 1
num_classes: 50
num_files: 1
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/AWA/std/dualda_1e-05
start_file: 9
validation_size: 2000
xai_method: dualda
