augmentation: rotate
base_epoch: 0
batch_size: 64
data_root: c:\Users\weckbecker\DualView-wip/src/datasets
dataset_name: AWA
dataset_type: std
device: cpu
epochs: 10
loss: cross_entropy
lr: 0.05
model_name: resnet50
model_path: /mnt/checkpoints/AWA/std/resnet50_std/resnet50_imagenet1k_v1.pth
momentum: 0
num_batches_eval: 200
num_classes: 50
optimizer: adam
save_dir: c:\Users\weckbecker\DualView-wip/checkpoints/AWA/std/resnet50_std
save_each: 2
scheduler: annealing
validation_size: 2000
weight_decay: 1.0e-05
