C: 1.0
accuracy: true
batch_size: 200
cache_dir: c:\Users\weckbecker\DualView-wip/cache/CIFAR/std/dualview_1.0
data_root: c:\Users\weckbecker\DualView-wip/../Datasets
dataset_name: CIFAR
dataset_type: std
device: cpu
features_dir: c:\Users\weckbecker\DualView-wip/cache/CIFAR/std/features
grad_dir: c:\Users\weckbecker\DualView-wip/cache/CIFAR/std/tracin/best
model_name: resnet18
model_path: c:\Users\weckbecker\DualView-wip/checkpoints/CIFAR/std/CIFAR_resnet18_best
num_batches_per_file: 1
num_classes: 10
num_files: 1
save_dir: c:\Users\weckbecker\DualView-wip/explanations/CIFAR/std/dualview_1.0
start_file: 9
validation_size: 2000
xai_method: dualview
