accuracy: true
batch_size: 20
data_root: /home/fe/yolcu/Documents/Code/DualView-wip/src/datasets
dataset_name: CIFAR
dataset_type: switched
device: cpu
model_name: resnet18
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/CIFAR/switched/CIFAR_resnet18
num_batches_per_file: 1
num_classes: 10
num_files: 1
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/CIFAR/switched/graddot
start_file: 0
validation_size: 2000
xai_method: graddot
