accuracy: true
batch_size: 16
data_root: c:\Users\weckbecker\DualView-wip/src/datasets
dataset_name: CIFAR
dataset_type: corrupt
device: cpu
model_name: resnet18
model_path: c:\Users\weckbecker\DualView-wip/checkpoints/CIFAR/corrupt/resnet18_corrupt/CIFAR_resnet18
num_batches_per_file: 1
num_classes: 10
num_files: 100
save_dir: c:\Users\weckbecker\DualView-wip/explanations/CIFAR/corrupt/resnet18_corrupt/rp_similarity
skip: 2230
start_file: 0
validation_size: 2000
xai_method: rp_similarity
