C: 0.1
accuracy: true
batch_size: 16
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: /home/yolcu/Documents/Code/DualView_wip/src/datasets
dataset_name: CIFAR
dataset_type: group
device: cpu
model_name: resnet18
model_path: /home/yolcu/Documents/Code/DualView_wip/checkpoints/CIFAR/group/CIFAR_resnet18_189
num_batches_per_file: 1
num_classes: 10
num_files: 1
save_dir: /home/yolcu/Documents/Code/DualView_wip/explanations/CIFAR/group/resnet18_group/dualview_0.1
start_file: 0
validation_size: 2000
xai_method: dualview
