accuracy: true
batch_size: 20
cache_dir: c:\Users\weckbecker\DualView-wip/cache/CIFAR/group/representer
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: c:\Users\weckbecker\DualView-wip/../Datasets
dataset_name: CIFAR
dataset_type: group
device: cpu
features_dir: c:\Users\weckbecker\DualView-wip/cache/CIFAR/group/features
grad_dir: c:\Users\weckbecker\DualView-wip/cache/CIFAR/group/tracin/best
model_name: resnet18
model_path: c:\Users\weckbecker\DualView-wip/checkpoints/CIFAR/group/CIFAR_resnet18_best
num_batches_per_file: 1
num_classes: 10
num_files: 1
save_dir: c:\Users\weckbecker\DualView-wip/explanations/CIFAR/group/representer
start_file: 99
validation_size: 2000
xai_method: representer
