accuracy: true
batch_size: 20
cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/CIFAR/corrupt/gradcos
data_root: /home/fe/yolcu/Documents/Code/DualView-wip/src/datasets
dataset_name: CIFAR
dataset_type: corrupt
device: cpu
features_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/corrupt/features
grad_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/corrupt/tracin/best
model_name: resnet18
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/CIFAR/corrupt/CIFAR_resnet18_best
num_batches_per_file: 1
num_classes: 10
num_files: 1
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/CIFAR/corrupt/gradcos
start_file: 99
validation_size: 2000
xai_method: gradcos
