C: 0.95
accuracy: true
batch_size: 20
cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/std/representer_0.95
data_root: /home/fe/yolcu/Documents/Code/DualView-wip/../Datasets
dataset_name: CIFAR
dataset_type: std
device: cpu
features_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/std/features
grad_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/std/tracin/best
model_name: resnet18
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/CIFAR/std/CIFAR_resnet18_best
num_batches_per_file: 1
num_classes: 10
num_files: 1
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/CIFAR/std/representer_0.95
start_file: 99
validation_size: 2000
xai_method: representer
