accuracy: true
batch_size: 16
data_root: /home/yolcu/Documents/Code/DualView_wip/src/datasets
dataset_name: CIFAR
dataset_type: corrupt
device: cpu
model_name: resnet18
model_path: /home/yolcu/Documents/Code/DualView_wip/checkpoints/CIFAR/corrupt/CIFAR_resnet18_189
num_batches_per_file: 1
num_classes: 10
num_files: 1
save_dir: /home/yolcu/Documents/Code/DualView_wip/explanations/CIFAR/corrupt/resnet18_corrupt/gradcos
start_file: 0
validation_size: 2000
xai_method: gradcos
