C: 1.0e-05
accuracy: true
batch_size: 32
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: /home/fe/yolcu/Documents/Code/Datasets/
dataset_name: CIFAR
dataset_type: mark
device: cuda
model_name: resnet
model_path: /home/fe/yolcu/Documents/Code/THESIS/checkpoints/CIFAR/mark/resnet_mark/CIFAR_resnet
num_batches_per_file: 1
num_classes: 10
num_files: 500
save_dir: /home/fe/yolcu/Documents/Code/THESIS/explanations/CIFAR/mark/resnet_mark/mcsvm_1e-05
skip: 2230
start_file: 0
validation_size: 2000
xai_method: mcsvm
