C: 0.001
accuracy: true
batch_size: 32
cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/std/dualview_0.001
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: /home/fe/yolcu/Documents/Code/Datasets
dataset_name: CIFAR
dataset_type: std
device: cuda
features_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/std/features
grad_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/std/tracin/best
model_name: resnet18
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/CIFAR/std/CIFAR_resnet18_best
num_batches_per_file: 100
num_classes: 10
num_files: 500
save_dir_explainer: /home/fe/yolcu/Documents/Code/DualView-wip/test_output
save_dir_results: /home/fe/yolcu/Documents/Code/DualView-wip/test_output
start_file: 0
validation_size: 2000
xai_method: dualview