augmentation: flip_rotate
base_epoch: 0
batch_size: 64
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: /home/yolcu/Documents/Code/DualXDA/src/datasets
dataset_name: CIFAR
dataset_type: mark
device: cpu
epochs: 10
loss: cross_entropy
lr: 0.01
model_name: resnet18
momentum: 0
num_batches_eval: 200
num_classes: 10
optimizer: adam
save_dir: /home/yolcu/Documents/Code/DualXDA/checkpoints/CIFAR/mark/resnet18_mark
save_each: 2
scheduler: constant
validation_size: 2000
weight_decay: 0
