C: '0.000001'
accuracy: true
batch_size: 32
cache_dir: /mnt/cache/MNIST/corrupt/dualview_0.000001
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: /mnt/dataset
dataset_name: MNIST
dataset_type: corrupt
device: cuda
features_dir: /mnt/cache/MNIST/corrupt/features
grad_dir: /mnt/cache/MNIST/corrupt/tracin/best
model_name: basic_conv
model_path: /mnt/checkpoints/MNIST/corrupt/MNIST_basic_conv_best
num_batches_per_file: 100
num_classes: 10
num_files: 500
save_dir_explainer: /mnt/outputs/MNIST/corrupt/dualview_0.000001_0.000001
save_dir_results: /mnt/outputs/MNIST/corrupt/dualview_0.000001_0.000001
start_file: 0
validation_size: 2000
xai_method: dualview
