C: '1'
accuracy: true
batch_size: 32
cache_dir: /mnt/cache/MNIST/std/dualview_1
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: /mnt/dataset
dataset_name: MNIST
dataset_type: std
device: cuda
features_dir: /mnt/cache/MNIST/std/features
grad_dir: /mnt/cache/MNIST/std/tracin/best
model_name: basic_conv
model_path: /mnt/checkpoints/MNIST/std/MNIST_basic_conv_best
num_batches_per_file: 100
num_classes: 10
num_files: 500
save_dir_explainer: /mnt/outputs/MNIST/std/dualview_1_1
save_dir_results: /mnt/outputs/MNIST/std/dualview_1_1
start_file: 0
validation_size: 2000
xai_method: dualview
