C: '0.0001'
accuracy: true
batch_size: 32
cache_dir: /mnt/cache/MNIST/group/dualview_0.0001
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: /mnt/dataset
dataset_name: MNIST
dataset_type: group
device: cuda
features_dir: /mnt/cache/MNIST/group/features
grad_dir: /mnt/cache/MNIST/group/tracin/best
model_name: basic_conv
model_path: /mnt/checkpoints/MNIST/group/MNIST_basic_conv_best
num_batches_per_file: 100
num_classes: 5
num_files: 500
save_dir_explainer: /mnt/outputs/MNIST/group/dualview_0.0001_0.0001
save_dir_results: /mnt/outputs/MNIST/group/dualview_0.0001_0.0001
start_file: 0
validation_size: 2000
xai_method: dualview
