C: 0.001
accuracy: true
batch_size: 200
cache_dir: /mnt/cache/MNIST/std/dualview_0.001
data_root: /mnt/dataset/
dataset_name: MNIST
dataset_type: std
device: cuda
features_dir: /mnt/cache/MNIST/std/features
grad_dir: /mnt/cache/MNIST/std/tracin/best
model_name: basic_conv
model_path: /mnt/checkpoints/MNIST/std/MNIST_basic_conv
num_batches_per_file: 1
num_classes: 10
num_files: 1
save_dir: /mnt/outputs/
start_file: 6
validation_size: 2000
xai_method: dualview
