C: 0.9
accuracy: true
batch_size: 20
cache_dir: /mnt/cache/MNIST/mark/representer_0.9
data_root: /mnt/dataset/
dataset_name: MNIST
dataset_type: mark
device: cuda
features_dir: /mnt/cache/MNIST/mark/features
grad_dir: /mnt/cache/MNIST/mark/tracin/best
model_name: basic_conv
model_path: /mnt/checkpoints/MNIST/mark/MNIST_basic_conv_best
num_batches_per_file: 1
num_classes: 10
num_files: 1
save_dir: /mnt/outputs/
start_file: 63
validation_size: 2000
xai_method: representer
