accuracy: true
batch_size: 20
cache_dir: /mnt/cache/MNIST/switched/tracin
data_root: /mnt/dataset/
dataset_name: MNIST
dataset_type: switched
device: cuda
features_dir: /mnt/cache/MNIST/switched/features
grad_dir: /mnt/cache/MNIST/switched/tracin/best
model_name: basic_conv
model_path: /mnt/checkpoints/MNIST/switched/MNIST_basic_conv
num_batches_per_file: 1
num_classes: 10
num_files: 1
save_dir: /mnt/outputs/
start_file: 97
validation_size: 2000
xai_method: graddot
