accuracy: true
batch_size: 16
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: /mnt/dataset/
dataset_name: MNIST
dataset_type: group
device: cuda
model_name: basic_conv
model_path: /mnt/checkpoints/MNIST/group/basic_conv_group/MNIST_basic_conv
num_batches_per_file: 1
num_classes: 10
num_files: 100
save_dir: /mnt/outputs/
skip: 2230
start_file: 0
validation_size: 2000
xai_method: rp_similarity
