C: 1.0e-05
accuracy: true
batch_size: 16
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: /mnt/dataset/
dataset_name: CIFAR
dataset_type: mark
device: cuda
model_name: resnet
model_path: /mnt/checkpoints/CIFAR/mark/resnet_mark/CIFAR_resnet
num_batches_per_file: 1
num_classes: 10
num_files: 1
save_dir: /mnt/outputs/
skip: 2230
start_file: 45
validation_size: 2000
xai_method: similarity
