C: 0.001
batch_size: 32
cache_dir: /home/yolcu/Documents/Code/DualXDA/cache/MNIST/corrupt/dualda_0.001
data_root: <data_root>
dataset_name: MNIST
dataset_type: corrupt
device: cpu
features_dir: /home/yolcu/Documents/Code/DualXDA/cache/MNIST/corrupt/features
grad_dir: /home/yolcu/Documents/Code/DualXDA/cache/MNIST/corrupt/tracin/best
lds_cache_dir: /home/yolcu/Documents/Code/DualXDA/cache/MNIST/mislabeling_detection
metric: mislabeling_detection
model_name: basic_conv
model_path: /home/yolcu/Documents/Code/DualXDA/checkpoints/MNIST/corrupt/MNIST_basic_conv_best
num_classes: 10
save_dir: /home/yolcu/Documents/Code/DualXDA/test_output
validation_size: 2000
xai_method: dualda
xpl_root: /home/yolcu/Documents/Code/DualXDA/explanations/MNIST/corrupt/dualda_0.001/
