C: 0.001
batch_size: 32
cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/std/dualview_0.001
data_root: <data_root>
dataset_name: MNIST
dataset_type: std
device: cpu
features_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/std/features
grad_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/std/tracin/best
lds_cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/coreset_selection
metric: coreset_selection
model_name: basic_conv
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/MNIST/std/MNIST_basic_conv_best
num_classes: 10
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/test_output
validation_size: 2000
xai_method: dualview
xpl_root: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/MNIST/std/dualview_0.001/
