augmentation: null
base_epoch: 0
batch_size: 64
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: /home/fe/yolcu/Documents/Code/DualView-wip/src/datasets
dataset_name: MNIST
dataset_type: std
device: cpu
epochs: 2
loss: cross_entropy
lr: 0.001
model_name: basic_conv
momentum: 0.9
num_batches_eval: 200
num_classes: 10
optimizer: sgd
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/MNIST/std/basic_conv_std
save_each: 1
scheduler: constant
validation_size: 2000
weight_decay: 0
