augmentation: crop_flip
base_epoch: 0
batch_size: 64
data_root: /home/fe/yolcu/Documents/Code/DualView-wip/src/datasets
dataset_name: MNIST
dataset_type: std
device: cpu
epochs: 2
loss: cross_entropy
lr: 0.001
model_name: basic_conv
momentum: 0
num_batches_eval: 200
num_classes: 10
optimizer: adam
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/MNIST/std/basic_conv_std
save_each: 1
scheduler: constant
validation_size: 2000
weight_decay: 0.01
