augmentation: crop_flip_rotate
base_epoch: 0
batch_size: 64
data_root: c:\Users\weckbecker\DualView-wip/src/datasets
dataset_name: MNIST
dataset_type: std
device: cpu
epochs: 10
loss: cross_entropy
lr: 0.01
model_name: basic_conv
momentum: 0.9
num_batches_eval: 200
num_classes: 10
optimizer: sgd
save_dir: c:\Users\weckbecker\DualView-wip/checkpoints/MNIST/std/basic_conv_std
save_each: 2
scheduler: annealing
validation_size: 2000
weight_decay: 1.0e-05
