augmentation: flip
batch_size: 16
cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/lds
data_root: /home/fe/yolcu/Documents/Code/DualView-wip/src/datasets
dataset_name: AWA
dataset_type: std
device: cpu
epochs: 50
loss: cross_entropy
lr: 0.01
metric: lds_cache
model_name: resnet50
momentum: 0.9
num_classes: 50
optimizer: sgd
sample_nr: 56
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/test_output
scheduler: annealing
validation_size: 2000
weight_decay: 0
