accuracy: true
batch_size: 20
cache_dir: /mnt/cache/tweet_sentiment_extraction/std/trak
data_root: /mnt/dataset/
dataset_name: tweet_sentiment_extraction
dataset_type: std
device: cuda
features_dir: /mnt/cache/tweet_sentiment_extraction/std/features
grad_dir: /mnt/cache/tweet_sentiment_extraction/std/tracin/best
model_name: GPT2
model_path: /mnt/checkpoints/tweet_sentiment_extraction/std/tweet_sentiment_extraction_GPT2_best
num_batches_per_file: 1
num_classes: GPT2
num_files: 1
save_dir: /mnt/outputs/
start_file: 40
validation_size: 2000
xai_method: trak
