augmentation: crop
batch_size: 16
cache_dir: /home/yolcu/Documents/Code/DualXDA/cache/MNIST/lds
data_root: <data_root>
dataset_name: MNIST
dataset_type: std
device: cpu
epochs: 200
loss: cross_entropy
lr: 0.005
metric: lds_cache
model_name: basic_conv
momentum: 0.9
num_classes: 10
optimizer: sgd
sample_nr: 95
save_dir: /home/yolcu/Documents/Code/DualXDA/cache/MNIST/lds
scheduler: constant
validation_size: 2000
weight_decay: 0
