batch_size: 32
cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/corrupt/kronfluence
data_root: ~/Documents/Code/Datasets
dataset_name: AWA
dataset_type: corrupt
device: cpu
features_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/corrupt/features
grad_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/corrupt/tracin/best
lds_cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/corrupt
metric: corrupt
model_name: resnet50
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/AWA/corrupt/AWA_resnet50_best
num_classes: 50
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/test_output
validation_size: 2000
xai_method: kronfluence
xpl_root: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/AWA/std/kronfluence/
