batch_size: 16
cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/mark/feature_similarity_l2
data_root: ~/Documents/Code/Datasets
dataset_name: AWA
dataset_type: mark
device: cpu
features_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/mark/features
grad_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/mark/tracin/best
lds_cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/mark
metric: mark
model_name: resnet50
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/AWA/mark/AWA_resnet50_best
num_classes: 50
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/test_output
validation_size: 2000
xai_method: feature_similarity_l2
xpl_root: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/AWA/mark/feature_similarity_l2/
