batch_size: 128
cache_dir: c:\Users\weckbecker\DualView-wip/cache/AWA/corrupt/representer
data_root: c:\Users\weckbecker\DualView-wip/src/datasets
dataset_name: AWA
dataset_type: corrupt
device: cpu
features_dir: c:\Users\weckbecker\DualView-wip/cache/AWA/corrupt/features
grad_dir: c:\Users\weckbecker\DualView-wip/cache/AWA/corrupt/tracin/best
metric: corrupt
model_name: resnet50
num_classes: 50
save_dir: c:\Users\weckbecker\DualView-wip/test_output
validation_size: 2000
xai_method: representer
xpl_root: c:\Users\weckbecker\DualView-wip/explanations/AWA/std/representer/
