C: 0.001
batch_size: 16
cache_dir: c:\Users\weckbecker\DualView-wip/cache/AWA/mark/dualview_0.001
data_root: c:\Users\weckbecker\DualView-wip/src/datasets
dataset_name: AWA
dataset_type: mark
device: cpu
features_dir: c:\Users\weckbecker\DualView-wip/cache/AWA/mark/features
grad_dir: c:\Users\weckbecker\DualView-wip/cache/AWA/mark/tracin/best
metric: mark
model_name: resnet50
model_path: c:\Users\weckbecker\DualView-wip/checkpoints/AWA/mark/resnet50_mark/AWA_resnet50_best
num_classes: 50
save_dir: c:\Users\weckbecker\DualView-wip/test_output
validation_size: 2000
xai_method: dualview
xpl_root: c:\Users\weckbecker\DualView-wip/explanations/AWA/mark/dualview/
