augmentation: flip
batch_size: 16
data_root: c:\Users\weckbecker\DualView-wip/src/datasets
dataset_name: AWA
device: cpu
epochs: 100
loss: cross_entropy
lr: 0.01
metric: lds
model_name: resnet50
momentum: 0
num_classes: 50
optimizer: sgd
save_dir: c:\Users\weckbecker\DualView-wip/test_output
scheduler: constant
validation_size: 2000
weight_decay: 0
xai_method: graddot
xpl_root: c:\Users\weckbecker\DualView-wip/explanations/AWA/std/resnet50_std/graddot
