C: 0.1
augmentation: flip
batch_size: 8
cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/std/dualview_0.1
data_root: ~/Documents/Code/Datasets
dataset_name: AWA
dataset_type: std
device: cpu
epochs: 30
features_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/std/features
grad_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/std/tracin/best
lds_cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/lds
loss: cross_entropy
lr: 0.001
metric: lds
model_name: resnet50
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/AWA/std/AWA_resnet50_best
momentum: 0.9
num_classes: 50
optimizer: sgd
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/test_output
scheduler: constant
validation_size: 2000
weight_decay: 0
xai_method: dualview
xpl_root: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/AWA/std/dualview_0.1/
