augmentation: flip
batch_size: 16
cache_dir: c:\Users\weckbecker\DualView-wip/cache/AWA/std/influence
data_root: c:\Users\weckbecker\DualView-wip/src/datasets
dataset_name: AWA
dataset_type: std
device: cpu
epochs: 50
features_dir: c:\Users\weckbecker\DualView-wip/cache/AWA/std/features
grad_dir: c:\Users\weckbecker\DualView-wip/cache/AWA/std/tracin/best
loss: cross_entropy
lr: 0.01
metric: leave_out
model_name: resnet50
momentum: 0.9
num_classes: 50
optimizer: sgd
save_dir: c:\Users\weckbecker\DualView-wip/test_output
scheduler: annealing
validation_size: 2000
weight_decay: 0
xai_method: influence
xpl_root: c:\Users\weckbecker\DualView-wip/explanations/AWA/std/influence/
