batch_size: 16
cache_dir: /mnt/src/cache/AWA/corrupt/lissa
data_root: /mnt/dataset
dataset_name: AWA
dataset_type: corrupt
device: cuda
features_dir: /mnt/src/cache/AWA/corrupt/features
grad_dir: /mnt/src/cache/AWA/corrupt/tracin/best
lds_cache_dir: /mnt/src/cache/AWA/corrupt
metric: corrupt
model_name: resnet50
model_path: /mnt/src/checkpoints/AWA/corrupt/AWA_resnet50_best
num_classes: 50
save_dir: /mnt/src/test_output
validation_size: 2000
xai_method: lissa
xpl_root: /mnt/src/explanations/AWA/corrupt/lissa/
