batch_size: 16
data_root: c:\Users\weckbecker\DualView-wip/src/datasets
dataset_name: AWA
device: cpu
metric: mark
model_name: resnet50
num_classes: 50
save_dir: c:\Users\weckbecker\DualView-wip/test_output
validation_size: 2000
xai_method: tracin
xpl_root: c:\Users\weckbecker\DualView-wip/explanations/AWA/mark/resnet50_mark/tracin
