augmentation: flip_rotate
base_epoch: 0
batch_size: 64
data_root: /mnt/dataset/
dataset_name: MNIST
dataset_type: std
device: cuda
epochs: 50
loss: cross_entropy
lr: 0.05
model_name: basic_conv
momentum: 0
num_batches_eval: 200
num_classes: 10
optimizer: sgd
save_dir: /mnt/outputs/
save_each: 5
scheduler: annealing
validation_size: 2000
weight_decay: 1.0e-05
