augmentation: crop
base_epoch: 0
batch_size: 64
data_root: /mnt/dataset/
dataset_name: MNIST
dataset_type: std
device: cuda
epochs: 20
loss: cross_entropy
lr: 0.0001
model_name: basic_conv
momentum: 0.9
num_batches_eval: 200
num_classes: 10
optimizer: adam
save_dir: /mnt/outputs/
save_each: 2
scheduler: constant
validation_size: 2000
weight_decay: 0
