augmentation: crop
base_epoch: 0
batch_size: 64
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: /mnt/dataset/
dataset_name: MNIST
dataset_type: mark
device: cuda
epochs: 190
loss: cross_entropy
lr: 0.005
model_name: basic_conv
momentum: 0.9
num_batches_eval: 200
num_classes: 10
optimizer: sgd
save_dir: /mnt/outputs/
save_each: 5
scheduler: constant
validation_size: 2000
weight_decay: 0
