C: 10
accuracy: true
batch_size: 200
cache_dir: /home/yolcu/Documents/Code/DualXDA/cache/CIFAR/std/dualda_10
data_root: <data_root>
dataset_name: CIFAR
dataset_type: std
device: cpu
features_dir: /home/yolcu/Documents/Code/DualXDA/cache/CIFAR/std/features
grad_dir: /home/yolcu/Documents/Code/DualXDA/cache/CIFAR/std/tracin/best
model_name: resnet18
model_path: /home/yolcu/Documents/Code/DualXDA/checkpoints/CIFAR/std/CIFAR_resnet18_best
num_batches_per_file: 1
num_classes: 10
num_files: 1
save_dir: /home/yolcu/Documents/Code/DualXDA/explanations/CIFAR/std/dualda_10
start_file: 3
validation_size: 2000
xai_method: dualda
