C: 1.0e-09
accuracy: true
batch_size: 200
cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/mark/dualview_1e-09
data_root: <data_root>
dataset_name: CIFAR
dataset_type: mark
device: cpu
features_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/mark/features
grad_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/mark/tracin/best
model_name: resnet18
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/CIFAR/mark/CIFAR_resnet18_best
num_batches_per_file: 1
num_classes: 10
num_files: 1
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/CIFAR/mark/dualview_1e-09
start_file: 5
validation_size: 2000
xai_method: dualview
