C: 1.0e-09
accuracy: true
batch_size: 200
cache_dir: /home/yolcu/Documents/Code/DualXDA/cache/CIFAR/mark/dualda_1e-09
data_root: <data_root>
dataset_name: CIFAR
dataset_type: mark
device: cpu
features_dir: /home/yolcu/Documents/Code/DualXDA/cache/CIFAR/mark/features
grad_dir: /home/yolcu/Documents/Code/DualXDA/cache/CIFAR/mark/tracin/best
model_name: resnet18
model_path: /home/yolcu/Documents/Code/DualXDA/checkpoints/CIFAR/mark/CIFAR_resnet18_best
num_batches_per_file: 1
num_classes: 10
num_files: 1
save_dir: /home/yolcu/Documents/Code/DualXDA/explanations/CIFAR/mark/dualda_1e-09
start_file: 9
validation_size: 2000
xai_method: dualda
