augmentation: flip
batch_size: 16
cache_dir: /mnt/outputs/AWA/lds
data_root: /mnt/dataset
dataset_name: AWA
dataset_type: std
device: cuda
epochs: 50
loss: cross_entropy
lr: 0.01
metric: lds_cache
model_name: resnet50
momentum: 0.9
num_classes: 50
optimizer: sgd
sample_nr: 18
save_dir: /mnt/outputs/
scheduler: annealing
validation_size: 2000
weight_decay: 0
