C: 0.1
batch_size: 16
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: /mnt/dataset
dataset_name: MNIST
device: cuda
metric: add_batch_in
model_name: basic_conv
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: influence
xpl_root: mnt/explanations/MNIST/std/basic_conv_std/influence
