C: 1.0e-05
batch_size: 16
cache_dir: /mnt/cache/MNIST/corrupt/dualview_1e_05
data_root: /mnt/dataset
dataset_name: MNIST
dataset_type: corrupt
device: cuda
features_dir: /mnt/cache/MNIST/corrupt/features
grad_dir: /mnt/cache/MNIST/corrupt/tracin/best
lds_cache_dir: /mnt/cache/MNIST/corrupt
metric: corrupt
model_name: basic_conv
model_path: /mnt/checkpoints/MNIST/corrupt/MNIST_basic_conv_best
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: dualview
xpl_root: /mnt/explanations/MNIST/std/dualview_1e_05/
