batch_size: 16
cache_dir: /mnt/cache/MNIST/corrupt/influence
data_root: /mnt/dataset
dataset_name: MNIST
dataset_type: corrupt
device: cuda
features_dir: /mnt/cache/MNIST/corrupt/features
grad_dir: /mnt/cache/MNIST/corrupt/tracin/best
metric: corrupt
model_name: basic_conv
model_path: /mnt/checkpoints/MNIST/corrupt/basic_conv_corrupt/MNIST_basic_conv
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: influence
xpl_root: /mnt/explanations/MNIST/std/influence/
