batch_size: 16
cache_dir: /mnt/cache/MNIST/std/input_similarity_cos
data_root: /mnt/dataset
dataset_name: MNIST
dataset_type: std
device: cuda
features_dir: /mnt/cache/MNIST/std/features
grad_dir: /mnt/cache/MNIST/std/tracin/best
lds_cache_dir: /mnt/cache/MNIST/lds
metric: lindatmod
model_name: basic_conv
model_path: /mnt/checkpoints/MNIST/std/MNIST_basic_conv_best
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: input_similarity_cos
xpl_root: /mnt/explanations/MNIST/std/input_similarity_cos/
