batch_size: 16
data_root: /mnt/dataset
dataset_name: MNIST
device: cuda
metric: stdk
model_name: basic_conv
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: trak
xpl_root: /mnt/explanations/MNIST/std/basic_conv_std/trak
