augmentation: crop
batch_size: 16
cache_dir: /mnt/cache/MNIST/std/trak
data_root: /mnt/dataset
dataset_name: MNIST
dataset_type: std
device: cuda
epochs: 200
features_dir: /mnt/cache/MNIST/std/features
grad_dir: /mnt/cache/MNIST/std/tracin/best
loss: cross_entropy
lr: 0.0016666666666666668
metric: add_batch_in_neg
model_name: basic_conv
momentum: 0.9
num_classes: 10
optimizer: sgd
save_dir: /mnt/outputs/
scheduler: constant
validation_size: 2000
weight_decay: 0
xai_method: trak
xpl_root: /mnt/explanations/MNIST/std/trak/
