batch_size: 16
cache_dir: /mnt/cache/MNIST/group/input_similarity_cos
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: /mnt/dataset
dataset_name: MNIST
dataset_type: group
device: cuda
features_dir: /mnt/cache/MNIST/group/features
grad_dir: /mnt/cache/MNIST/group/tracin/best
lds_cache_dir: /mnt/cache/MNIST/lds
metric: group
model_name: basic_conv
model_path: /mnt/checkpoints/MNIST/group/MNIST_basic_conv_best
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: input_similarity_cos
xpl_root: /mnt/explanations/MNIST/group/input_similarity_cos/
