batch_size: 16
cache_dir: /mnt/cache/MNIST/std/gradcos
data_root: /mnt/dataset
dataset_name: MNIST
dataset_type: std
device: cuda
features_dir: /mnt/cache/MNIST/std/features
grad_dir: /mnt/cache/MNIST/std/tracin/best
metric: std
model_name: basic_conv
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: gradcos
xpl_root: /mnt/explanations/MNIST/std/gradcos/
