augmentation: crop
batch_size: 16
data_root: /mnt/dataset
dataset_name: MNIST
dataset_type: std
device: cuda
epochs: 200
loss: cross_entropy
lr: 0.005
metric: add_batch_in_neg
model_name: basic_conv
momentum: 0.9
num_classes: 10
optimizer: sgd
save_dir: /mnt/outputs/
scheduler: constant
validation_size: 2000
weight_decay: 0
xai_method: tracin
xpl_root: /mnt/xpl/MNIST/std/tracin/
