C: 1
batch_size: 16
data_root: /mnt/dataset
dataset_name: MNIST
dataset_type: std
device: cuda
metric: stdk
model_name: basic_conv
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: dualview
xpl_root: /mnt/xpl/MNIST/std/dualview/
