C: 0.1
batch_size: 128
cache_dir: /mnt/cache/MNIST/mark/representer
data_root: /mnt/dataset
dataset_name: MNIST
dataset_type: mark
device: cuda
features_dir: /mnt/cache/MNIST/mark/features
grad_dir: /mnt/cache/MNIST/mark/tracin/best
lds_cache_dir: /mnt/cache/MNIST/mark
metric: mark
model_name: basic_conv
model_path: /mnt/checkpoints/MNIST/mark/MNIST_basic_conv_best
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: representer
xpl_root: /mnt/explanations/MNIST/mark/representer/
