batch_size: 128
data_root: /mnt/dataset
dataset_name: MNIST
device: cuda
metric: std
model_name: basic_conv
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: representer
xpl_root: mnt/explanations/MNIST/std/basic_conv_std/representer
