batch_size: 16
data_root: /mnt/dataset
dataset_name: MNIST
device: cuda
metric: mark
model_name: basic_conv
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: tracin
xpl_root: mnt/explanations/MNIST/mark/basic_conv_mark/tracin
