batch_size: 128
cache_dir: /mnt/cache/MNIST/corrupt/representer
data_root: /mnt/dataset
dataset_name: MNIST
dataset_type: corrupt
device: cuda
features_dir: /mnt/cache/MNIST/corrupt/features
grad_dir: /mnt/cache/MNIST/corrupt/tracin/best
metric: corrupt
model_name: basic_conv
model_path: /mnt/checkpoints/MNIST/corrupt/MNIST_basic_conv_best
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: representer
xpl_root: /mnt/explanations/MNIST/std/representer/
