batch_size: 16
cache_dir: /mnt/cache/MNIST/corrupt/input_similarity_cos
data_root: /mnt/dataset
dataset_name: MNIST
dataset_type: corrupt
device: cuda
features_dir: /mnt/cache/MNIST/corrupt/features
grad_dir: /mnt/cache/MNIST/corrupt/tracin/best
metric: corrupt
model_name: basic_conv
model_path: /mnt/checkpoints/MNIST/corrupt/MNIST_basic_conv_best
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: input_similarity_cos
xpl_root: /mnt/explanations/MNIST/std/input_similarity_cos/
