C: 0.001
batch_size: 16
cache_dir: /mnt/cache/MNIST/lds
data_root: /mnt/dataset
dataset_name: MNIST
dataset_type: mark
device: cuda
features_dir: /mnt/cache/MNIST/mark/features
grad_dir: /mnt/cache/MNIST/mark/tracin/best
lds_cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/MNIST/lds
metric: mark
model_name: basic_conv
model_path: /mnt/checkpoints/MNIST/mark/MNIST_basic_conv_best
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: dualview
xpl_root: /mnt/explanations/MNIST/mark/dualview_0.001/
