augmentation: flip
batch_size: 16
data_root: /mnt/dataset
dataset_name: MNIST
device: cuda
epochs: 100
loss: cross_entropy
lr: 0.01
metric: add_batch_in
model_name: basic_conv
momentum: 0
num_classes: 10
optimizer: sgd
save_dir: /mnt/outputs/
scheduler: constant
validation_size: 2000
weight_decay: 0
xai_method: tracin
xpl_root: mnt/explanations/MNIST/std/basic_conv_std/tracin
