augmentation: crop
batch_size: 8
cache_dir: /mnt/cache/MNIST/lds
data_root: /mnt/dataset
dataset_name: MNIST
dataset_type: std
device: cuda
epochs: 200
features_dir: /mnt/cache/MNIST/std/features
grad_dir: /mnt/cache/MNIST/std/tracin/best
loss: cross_entropy
lr: 0.0016666666666666668
metric: leave_out
model_name: basic_conv
model_path: /mnt/checkpoints/MNIST/std/MNIST_basic_conv_best
momentum: 0.9
num_classes: 10
optimizer: sgd
save_dir: /mnt/outputs/
scheduler: constant
validation_size: 2000
weight_decay: 0
xai_method: input_similarity_l2
xpl_root: /mnt/explanations/MNIST/std/input_similarity_l2/
