batch_size: 16
cache_dir: /mnt/cache/MNIST/std/feature_similarity_dot
data_root: /mnt/dataset
dataset_name: MNIST
dataset_type: std
device: cuda
features_dir: /mnt/cache/MNIST/std/features
grad_dir: /mnt/cache/MNIST/std/tracin/best
lds_cache_dir: /mnt/cache/MNIST/lds
metric: std
model_name: basic_conv
model_path: /mnt/checkpoints/MNIST/std/MNIST_basic_conv_best
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: feature_similarity_dot
xpl_root: /mnt/explanations/MNIST/std/feature_similarity_dot/
