batch_size: 16
cache_dir: /mnt/cache/MNIST/group/influence
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: /mnt/dataset
dataset_name: MNIST
dataset_type: group
device: cuda
features_dir: /mnt/cache/MNIST/group/features
grad_dir: /mnt/cache/MNIST/group/tracin/best
metric: groupk
model_name: basic_conv
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: influence
xpl_root: /mnt/explanations/MNIST/group/influence/
