C: 0.1
batch_size: 16
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: c:\Users\weckbecker\DualView-wip/src/datasets
dataset_name: CIFAR
device: cpu
metric: group
model_name: resnet18
num_classes: 10
save_dir: c:\Users\weckbecker\DualView-wip/test_output
validation_size: 2000
xai_method: dualview
xpl_root: c:\Users\weckbecker\DualView-wip/explanations/CIFAR/group/resnet18_group/dualview_0.1
