batch_size: 16
cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/corrupt/input_similarity_l2
data_root: ~/Documents/Code/Datasets
dataset_name: CIFAR
dataset_type: corrupt
device: cpu
features_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/corrupt/features
grad_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/corrupt/tracin/best
lds_cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/corrupt
metric: corrupt
model_name: resnet18
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/CIFAR/corrupt/CIFAR_resnet18_best
num_classes: 10
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/test_output
validation_size: 2000
xai_method: input_similarity_l2
xpl_root: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/CIFAR/std/input_similarity_l2/
