augmentation: crop_flip
batch_size: 8
cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/std/kronfluence
data_root: ~/Documents/Code/Datasets
dataset_name: CIFAR
dataset_type: std
device: cpu
epochs: 190
features_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/std/features
grad_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/std/tracin/best
lds_cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/add_batch_in_neg
loss: cross_entropy
lr: 0.0003333333333333333
metric: add_batch_in_neg
model_name: resnet18
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/CIFAR/std/CIFAR_resnet18_best
momentum: 0.9
num_classes: 10
optimizer: sgd
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/test_output
scheduler: constant
validation_size: 2000
weight_decay: 0.01
xai_method: kronfluence
xpl_root: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/CIFAR/std/kronfluence/
