augmentation: crop_flip
batch_size: 16
cache_dir: c:\Users\weckbecker\DualView-wip/cache/CIFAR/std/trak
data_root: c:\Users\weckbecker\DualView-wip/src/datasets
dataset_name: CIFAR
dataset_type: std
device: cpu
epochs: 190
features_dir: c:\Users\weckbecker\DualView-wip/cache/CIFAR/std/features
grad_dir: c:\Users\weckbecker\DualView-wip/cache/CIFAR/std/tracin/best
loss: cross_entropy
lr: 0.001
metric: add_batch_in_neg
model_name: resnet18
momentum: 0.9
num_classes: 10
optimizer: sgd
save_dir: c:\Users\weckbecker\DualView-wip/test_output
scheduler: constant
validation_size: 2000
weight_decay: 0.01
xai_method: trak
xpl_root: c:\Users\weckbecker\DualView-wip/explanations/CIFAR/std/trak/
