batch_size: 128
cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/std/representer
data_root: ~/Documents/Code/Datasets
dataset_name: CIFAR
dataset_type: std
device: cpu
features_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/std/features
grad_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/std/tracin/best
lds_cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/lindatmod
metric: lindatmod
model_name: resnet18
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/CIFAR/std/CIFAR_resnet18_best
num_classes: 10
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/test_output
validation_size: 2000
xai_method: representer
xpl_root: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/CIFAR/std/representer/
