batch_size: 16
cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/group/input_similarity_l2
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: ~/Documents/Code/Datasets
dataset_name: CIFAR
dataset_type: group
device: cpu
features_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/group/features
grad_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/group/tracin/best
lds_cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/groupk
metric: groupk
model_name: resnet18
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/CIFAR/group/CIFAR_resnet18_best
num_classes: 10
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/test_output
validation_size: 2000
xai_method: input_similarity_l2
xpl_root: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/CIFAR/group/input_similarity_l2/
