C: '0.00001'
accuracy: true
batch_size: 32
cache_dir: /mnt/cache/AWA/mark/representer
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: /mnt/dataset
dataset_name: AWA
dataset_type: mark
device: cuda
features_dir: /mnt/cache/AWA/mark/features
grad_dir: /mnt/cache/AWA/mark/tracin/best
model_name: resnet50
model_path: /mnt/checkpoints/AWA/mark/AWA_resnet50_best
num_batches_per_file: 100
num_classes: 50
num_files: 500
save_dir_explainer: /mnt/outputs/AWA/mark/representer_0.00001
save_dir_results: /mnt/outputs/AWA/mark/representer_0.00001
start_file: 0
validation_size: 2000
xai_method: representer
