batch_size: 16
data_root: /mnt/dataset
dataset_name: CIFAR
dataset_type: switched
device: cuda
metric: switched
model_name: resnet18
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: graddot
xpl_root: /mnt/xpl/CIFAR/switched_one_file/graddot/
