batch_size: 128
data_root: /mnt/dataset
dataset_name: CIFAR
device: cuda
metric: corrupt
model_name: resnet18
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: representer
xpl_root: mnt/explanations/CIFAR/std/resnet18_std/representer
