augmentation: flip
batch_size: 16
data_root: /mnt/dataset
dataset_name: CIFAR
device: cuda
epochs: 100
loss: cross_entropy
lr: 0.01
metric: labelflip
model_name: resnet18
momentum: 0
num_classes: 10
optimizer: sgd
save_dir: /mnt/outputs/
scheduler: constant
validation_size: 2000
weight_decay: 0
xai_method: influence
xpl_root: mnt/explanations/CIFAR/std/resnet18_std/influence
