batch_size: 128
cache_dir: /mnt/cache/CIFAR/group/representer
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: /mnt/dataset
dataset_name: CIFAR
dataset_type: group
device: cuda
features_dir: /mnt/cache/CIFAR/group/features
grad_dir: /mnt/cache/CIFAR/group/tracin/best
metric: groupk
model_name: resnet18
model_path: /mnt/checkpoints/CIFAR/group/resnet18_groupk/CIFAR_resnet18
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: representer
xpl_root: /mnt/explanations/CIFAR/group/representer/
