C: 0.1
batch_size: 16
data_root: /mnt/dataset
dataset_name: CIFAR
device: cuda
metric: std
model_name: resnet18
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: dualview
xpl_root: mnt/explanations/CIFAR/std/resnet18_std/dualview_0.1
