C: 0.1
batch_size: 16
cache_dir: /mnt/cache/CIFAR/corrupt/dualview_0.1
data_root: /mnt/dataset
dataset_name: CIFAR
dataset_type: corrupt
device: cpu
features_dir: /mnt/cache/CIFAR/corrupt/features
grad_dir: /mnt/cache/CIFAR/corrupt/tracin/best
lds_cache_dir: /mnt/cache/CIFAR/lds
metric: corrupt
model_name: resnet18
model_path: /mnt/checkpoints/CIFAR/corrupt/CIFAR_resnet18_best
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: dualview
xpl_root: /mnt/explanations/CIFAR/std/dualview_0.1/
