augmentation: crop_flip
batch_size: 16
cache_dir: /mnt/cache/CIFAR/std/trak
data_root: /mnt/dataset
dataset_name: CIFAR
dataset_type: std
device: cuda
epochs: 190
features_dir: /mnt/cache/CIFAR/std/features
grad_dir: /mnt/cache/CIFAR/std/tracin/best
loss: cross_entropy
lr: 0.001
metric: add_batch_in
model_name: resnet18
momentum: 0.9
num_classes: 10
optimizer: sgd
save_dir: /mnt/outputs/
scheduler: constant
validation_size: 2000
weight_decay: 0.01
xai_method: trak
xpl_root: /mnt/explanations/CIFAR/std/trak/
