batch_size: 16
cache_dir: /mnt/cache/CIFAR/std/tracin
data_root: /mnt/dataset
dataset_name: CIFAR
dataset_type: std
device: cuda
features_dir: /mnt/cache/CIFAR/std/features
grad_dir: /mnt/cache/CIFAR/std/tracin/best
metric: std
model_name: resnet18
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: tracin
xpl_root: /mnt/explanations/CIFAR/std/tracin/
