batch_size: 16
cache_dir: /mnt/cache/CIFAR/std/gradcos
data_root: /mnt/dataset
dataset_name: CIFAR
dataset_type: std
device: cuda
features_dir: /mnt/cache/CIFAR/std/features
grad_dir: /mnt/cache/CIFAR/std/tracin/best
metric: stdk
model_name: resnet18
model_path: /mnt/checkpoints/CIFAR/std/resnet18_stdk/CIFAR_resnet18
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: gradcos
xpl_root: /mnt/explanations/CIFAR/std/gradcos/
