batch_size: 16
data_root: /mnt/dataset
dataset_name: CIFAR
device: cuda
metric: mark
model_name: resnet18
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: trak
xpl_root: /mnt/explanations/CIFAR/mark/resnet18_mark/trak
