batch_size: 16
cache_dir: /mnt/cache/CIFAR/std/lissa
data_root: /mnt/dataset
dataset_name: CIFAR
dataset_type: std
device: cuda
features_dir: /mnt/cache/CIFAR/std/features
grad_dir: /mnt/cache/CIFAR/std/tracin/best
lds_cache_dir: /mnt/cache/CIFAR/lindatmod
metric: lindatmod
model_name: resnet18
model_path: /mnt/checkpoints/CIFAR/std/CIFAR_resnet18_best
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: lissa
xpl_root: /mnt/explanations/CIFAR/std/lissa/
