C: 0.1
batch_size: 128
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
coef_root: mnt/explanations/CIFAR/group/resnet18_group/representer
data_root: /mnt/dataset
dataset_name: CIFAR
device: cuda
metric: group
model_name: resnet18
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: representer
xpl_root: mnt/explanations/CIFAR/group/resnet18_group/representer
