batch_size: 16
cache_dir: /mnt/cache/CIFAR/mark/tracin
data_root: /mnt/dataset
dataset_name: CIFAR
dataset_type: mark
device: cuda
features_dir: /mnt/cache/CIFAR/mark/features
grad_dir: /mnt/cache/CIFAR/mark/tracin/best
metric: mark
model_name: resnet18
model_path: /mnt/checkpoints/CIFAR/mark/resnet18_mark/CIFAR_resnet18
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: tracin
xpl_root: /mnt/explanations/CIFAR/mark/tracin/
