batch_size: 16
cache_dir: /mnt/cache/CIFAR/corrupt/tracin
data_root: /mnt/dataset
dataset_name: CIFAR
dataset_type: corrupt
device: cuda
features_dir: /mnt/cache/CIFAR/corrupt/features
grad_dir: /mnt/cache/CIFAR/corrupt/tracin/best
metric: corrupt
model_name: resnet18
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: graddot
xpl_root: /mnt/explanations/CIFAR/std/graddot/
