batch_size: 16
cache_dir: /mnt/cache/CIFAR/corrupt/arnoldi
data_root: /mnt/dataset
dataset_name: CIFAR
dataset_type: corrupt
device: cuda
features_dir: /mnt/cache/CIFAR/corrupt/features
grad_dir: /mnt/cache/CIFAR/corrupt/tracin/best
metric: corrupt
model_name: resnet18
model_path: /mnt/checkpoints/CIFAR/corrupt/resnet18_corrupt/CIFAR_resnet18
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: arnoldi
xpl_root: /mnt/explanations/CIFAR/std/arnoldi/
