C: 1.0e-09
batch_size: 32
cache_dir: /mnt/cache/CIFAR/mark/dualview_1e-09
data_root: /mnt/dataset
dataset_name: CIFAR
dataset_type: mark
device: cuda
features_dir: /mnt/cache/CIFAR/mark/features
grad_dir: /mnt/cache/CIFAR/mark/tracin/best
lds_cache_dir: /mnt/cache/CIFAR/mark
metric: mark
model_name: resnet18
model_path: /mnt/checkpoints/CIFAR/mark/CIFAR_resnet18_best
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: dualview
xpl_root: /mnt/explanations/CIFAR/mark/dualview_1e-09/
