C: 0.01
batch_size: 16
cache_dir: /mnt/cache/CIFAR/std/dualview_0.01
data_root: /mnt/dataset
dataset_name: CIFAR
dataset_type: std
device: cuda
features_dir: /mnt/cache/CIFAR/std/features
grad_dir: /mnt/cache/CIFAR/std/tracin/best
metric: std
model_name: resnet18
model_path: /mnt/checkpoints/CIFAR/std/CIFAR_resnet18_best
num_classes: 10
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: dualview
xpl_root: /mnt/explanations/CIFAR/std/dualview_0.01/
