augmentation: crop
batch_size: 16
cache_dir: /mnt/outputs/MNIST/lds
data_root: /mnt/dataset
dataset_name: MNIST
dataset_type: std
device: cuda
epochs: 200
loss: cross_entropy
lr: 0.005
metric: lds_cache
model_name: basic_conv
momentum: 0.9
num_classes: 10
optimizer: sgd
sample_nr: 74
save_dir: /mnt/outputs/
scheduler: constant
validation_size: 2000
weight_decay: 0
