augmentation: rotate
base_epoch: 0
batch_size: 64
data_root: /mnt/dataset/
dataset_name: CIFAR
dataset_type: std
device: cuda
epochs: 20
loss: cross_entropy
lr: 0.005
model_name: resnet18
momentum: 0.9
num_batches_eval: 200
num_classes: 10
optimizer: sgd
save_dir: /mnt/outputs/
save_each: 2
scheduler: constant
validation_size: 2000
weight_decay: 0
