augmentation: flip_rotate
base_epoch: 0
batch_size: 64
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: /mnt/dataset/
dataset_name: CIFAR
dataset_type: corrupt
device: cuda
epochs: 200
loss: cross_entropy
lr: 0.001
model_name: resnet18
momentum: 0
num_batches_eval: 200
num_classes: 10
optimizer: sgd
save_dir: /mnt/outputs/
save_each: 10
scheduler: constant
validation_size: 2000
weight_decay: 0.01
