base_epoch: 0
batch_size: 128
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: /mnt/dataset/
dataset_name: CIFAR
dataset_type: mark
device: cuda
epochs: 150
lr: 0.005
augmentation: cifar
model_name: resnet18
num_batches_eval: 200
num_classes: 10
num_saves: 1
save_dir: /mnt/outputs/
save_each: 10
validation_size: 2000
