augmentation: crop_flip_rotate
base_epoch: 0
batch_size: 64
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: /home/fe/yolcu/Documents/Code/DualView-wip/src/datasets
dataset_name: MNIST
dataset_type: mark
device: cpu
epochs: 10
loss: cross_entropy
lr: 0.01
model_name: basic_conv
momentum: 0.9
num_batches_eval: 200
num_classes: 10
optimizer: adam
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/MNIST/mark/basic_conv_mark
save_each: 2
scheduler: step
validation_size: 2000
weight_decay: 0.0001
