augmentation: crop_rotate
base_epoch: 0
batch_size: 64
data_root: /home/yolcu/Documents/Code/DualXDA/src/datasets
dataset_name: MNIST
dataset_type: std
device: cpu
epochs: 10
loss: cross_entropy
lr: 0.05
model_name: basic_conv
momentum: 0
num_batches_eval: 200
num_classes: 10
optimizer: adam
save_dir: /home/yolcu/Documents/Code/DualXDA/checkpoints/MNIST/std/basic_conv_std
save_each: 2
scheduler: step
validation_size: 2000
weight_decay: 0.0001
