augmentation: rotate
base_epoch: 0
batch_size: 64
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: /home/yolcu/Documents/Code/DualXDA/src/datasets
dataset_name: MNIST
dataset_type: group
device: cpu
epochs: 10
loss: cross_entropy
lr: 0.005
model_name: basic_conv
momentum: 0
num_batches_eval: 200
num_classes: 10
optimizer: sgd
save_dir: /home/yolcu/Documents/Code/DualXDA/checkpoints/MNIST/group/basic_conv_group
save_each: 2
scheduler: annealing
validation_size: 2000
weight_decay: 0
