accuracy: true
batch_size: 20
cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/switched/influence
data_root: /home/fe/yolcu/Documents/Code/DualView-wip/src/datasets
dataset_name: AWA
dataset_type: switched
device: cpu
features_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/switched/features
grad_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/switched/tracin/best
model_name: resnet50
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/AWA/switched/AWA_resnet50_best
num_batches_per_file: 1
num_classes: 50
num_files: 1
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/AWA/switched/influence
start_file: 99
validation_size: 2000
xai_method: influence
