accuracy: true
batch_size: 20
data_root: /home/fe/yolcu/Documents/Code/DualView-wip/src/datasets
dataset_name: AWA
dataset_type: switched
device: cpu
model_name: resnet50
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/AWA/switched/AWA_resnet50
num_batches_per_file: 1
num_classes: 50
num_files: 1
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/AWA/switched/trak
start_file: 0
validation_size: 2000
xai_method: trak
