accuracy: true
batch_size: 20
cache_dir: c:\Users\weckbecker\DualView-wip/cache/AWA/corrupt/tracin
data_root: c:\Users\weckbecker\DualView-wip/../Datasets
dataset_name: AWA
dataset_type: corrupt
device: cpu
features_dir: c:\Users\weckbecker\DualView-wip/cache/AWA/corrupt/features
grad_dir: c:\Users\weckbecker\DualView-wip/cache/AWA/corrupt/tracin/best
model_name: resnet50
model_path: c:\Users\weckbecker\DualView-wip/checkpoints/AWA/corrupt/AWA_resnet50_best
num_batches_per_file: 1
num_classes: 50
num_files: 1
save_dir: c:\Users\weckbecker\DualView-wip/explanations/AWA/corrupt/tracin
start_file: 99
validation_size: 2000
xai_method: tracin
