accuracy: true
batch_size: 16
data_root: c:\Users\weckbecker\DualView-wip/src/datasets
dataset_name: AWA
dataset_type: std
device: cpu
model_name: resnet50
model_path: c:\Users\weckbecker\DualView-wip/checkpoints/AWA/std/resnet50_std/AWA_resnet50
num_batches_per_file: 1
num_classes: 50
num_files: 100
save_dir: c:\Users\weckbecker\DualView-wip/explanations/AWA/std/resnet50_std/trak
skip: 2230
start_file: 0
validation_size: 2000
xai_method: trak
