C: 0.001
accuracy: true
batch_size: 200
cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/std/representer_0.001
data_root: /home/fe/yolcu/Documents/Code/DualView-wip/../Datasets
dataset_name: AWA
dataset_type: std
device: cpu
features_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/std/features
grad_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/AWA/std/tracin/best
model_name: resnet50
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/AWA/std/AWA_resnet50_best
num_batches_per_file: 1
num_classes: 50
num_files: 1
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/AWA/std/representer_0.001
start_file: 9
validation_size: 2000
xai_method: representer
