accuracy: true
batch_size: 5
cache_dir: /home/yolcu/Documents/Code/DualXDA/cache/AWA/std/lissa
data_root: /home/yolcu/Documents/Code/DualXDA/../Datasets
dataset_name: AWA
dataset_type: std
device: cuda
features_dir: /home/yolcu/Documents/Code/DualXDA/cache/AWA/std/features
grad_dir: /home/yolcu/Documents/Code/DualXDA/cache/AWA/std/tracin/best
model_name: resnet50
model_path: /home/yolcu/Documents/Code/DualXDA/checkpoints/AWA/std/AWA_resnet50_best
num_batches_per_file: 1
num_classes: 50
num_files: 1
save_dir: /home/yolcu/Documents/Code/DualXDA/explanations/AWA/std/lissa
start_file: 399
validation_size: 2000
xai_method: lissa
