accuracy: true
batch_size: 16
data_root: /home/yolcu/Documents/Code/DualView_wip/src/datasets
dataset_name: AWA
dataset_type: mark
device: cpu
model_name: resnet50
model_path: /home/yolcu/Documents/Code/DualView_wip/checkpoints/AWA/mark/AWA_resnet50_29
num_batches_per_file: 1
num_classes: 50
num_files: 1
save_dir: /home/yolcu/Documents/Code/DualView_wip/explanations/AWA/mark/resnet50_mark/tracin
start_file: 0
validation_size: 2000
xai_method: tracin
