accuracy: true
batch_size: 128
data_root: c:\Users\weckbecker\DualView-wip/src/datasets
dataset_name: AWA
dataset_type: switched_one_file
device: cpu
model_name: resnet50
model_path: c:\Users\weckbecker\DualView-wip/checkpoints/AWA/switched_one_file/resnet50_switched_one_file/AWA_resnet50
num_batches_per_file: 1
num_classes: 50
num_files: 100
save_dir: c:\Users\weckbecker\DualView-wip/explanations/AWA/switched_one_file/resnet50_switched_one_file/representer
skip: 2230
start_file: 0
validation_size: 2000
xai_method: representer
