accuracy: true
batch_size: 16
data_root: c:\Users\weckbecker\DualView-wip/src/datasets
dataset_name: AWA
dataset_type: corrupt
device: cpu
model_name: resnet50
model_path: c:\Users\weckbecker\DualView-wip/checkpoints/AWA/corrupt/resnet50_corrupt/AWA_resnet50
num_batches_per_file: 1
num_classes: 50
num_files: 100
save_dir: c:\Users\weckbecker\DualView-wip/explanations/AWA/corrupt/resnet50_corrupt/rp_similarity
skip: 2230
start_file: 0
validation_size: 2000
xai_method: rp_similarity
