accuracy: true
batch_size: 4
cache_dir: /home/yolcu/Documents/Code/DualXDA/cache/ag_news_shortcut/kronfluence_28
data_root: /home/yolcu/Documents/Code/DualXDA/../Datasets
dataset_name: ag_news_shortcut2000
dataset_type: std
device: cuda
features_dir: /home/yolcu/Documents/Code/DualXDA/cache/ag_news/std/features
grad_dir: /home/yolcu/Documents/Code/DualXDA/cache/ag_news/std/tracin/best
hf_id: MoritzWeckbecker/llama-ag_news-shortcut-4000-20percent-0
model_path: /home/yolcu/Documents/Code/DualXDA/checkpoints/ag_news/std/ag_news_None_best
num_batches_per_file: 1
num_files: 5000
save_dir: /home/yolcu/Documents/Code/DualXDA/explanations/ag_news_shortcut/kronfluence_28
start_file: 0
validation_size: 2000
xai_method: kronfluence_28
