augmentation: flip
batch_size: 16
cache_dir: /home/yolcu/Documents/Code/DualXDA/cache/AWA/lds
data_root: <data_root>
dataset_name: AWA
dataset_type: std
device: cpu
epochs: 50
loss: cross_entropy
lr: 0.01
metric: lds_cache
model_name: resnet50
momentum: 0.9
num_classes: 50
optimizer: sgd
sample_nr: 14
save_dir: /home/yolcu/Documents/Code/DualXDA/cache/AWA/lds
scheduler: annealing
validation_size: 2000
weight_decay: 0
