C: 0.1
batch_size: 128
cache_dir: /home/yolcu/DualView_wip/cache/MNIST/group/representer
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: /media/yolcu/
dataset_name: MNIST
dataset_type: group
device: cuda
features_dir: /home/yolcu/DualView_wip/cache/MNIST/group/features
grad_dir: /home/yolcu/DualView_wip/cache/MNIST/group/tracin/best
lds_cache_dir: /home/yolcu/DualView_wip/cache/MNIST/groupk
metric: groupk
model_name: basic_conv
model_path: /home/yolcu/DualView_wip/checkpoints/MNIST/group/MNIST_basic_conv_best
num_classes: 10
save_dir: /home/yolcu/DualView_wip/test_output/representer_0.1
validation_size: 2000
xai_method: representer
xpl_root: /home/yolcu/DualView_wip/explanations/MNIST/group/representer_0.1/
