C: 0.001
batch_size: 32
cache_dir: /home/yolcu/DualView_wip/cache/MNIST/mark/dualview_0.001
data_root: /media/yolcu/
dataset_name: MNIST
dataset_type: mark
device: cuda
features_dir: /home/yolcu/DualView_wip/cache/MNIST/mark/features
grad_dir: /home/yolcu/DualView_wip/cache/MNIST/mark/tracin/best
lds_cache_dir: /home/yolcu/DualView_wip/cache/MNIST/shortcut_detection
metric: shortcut_detection
model_name: basic_conv
model_path: /home/yolcu/DualView_wip/checkpoints/MNIST/mark/MNIST_basic_conv_best
num_classes: 10
save_dir: /home/yolcu/DualView_wip/test_output/dualview_0.001
validation_size: 2000
xai_method: dualview
xpl_root: /home/yolcu/DualView_wip/explanations/MNIST/mark/dualview_0.001/
