C: 1.0e-05
augmentation: crop
batch_size: 8
cache_dir: /home/yolcu/DualView_wip/cache/MNIST/std/representer
data_root: /media/yolcu/
dataset_name: MNIST
dataset_type: std
device: cuda
epochs: 200
features_dir: /home/yolcu/DualView_wip/cache/MNIST/std/features
grad_dir: /home/yolcu/DualView_wip/cache/MNIST/std/tracin/best
lds_cache_dir: /home/yolcu/DualView_wip/cache/MNIST/lds
loss: cross_entropy
lr: 0.0016666666666666668
metric: lds
model_name: basic_conv
model_path: /home/yolcu/DualView_wip/checkpoints/MNIST/std/MNIST_basic_conv_best
momentum: 0.9
num_classes: 10
optimizer: sgd
save_dir: /home/yolcu/DualView_wip/test_output/representer_1e-05
scheduler: constant
validation_size: 2000
weight_decay: 0
xai_method: representer
xpl_root: /home/yolcu/DualView_wip/explanations/MNIST/std/representer_1e-05/
