C: 0.1
batch_size: 128
cache_dir: /home/yolcu/DualView_wip/cache/MNIST/corrupt/representer
data_root: /media/yolcu/
dataset_name: MNIST
dataset_type: corrupt
device: cuda
features_dir: /home/yolcu/DualView_wip/cache/MNIST/corrupt/features
grad_dir: /home/yolcu/DualView_wip/cache/MNIST/corrupt/tracin/best
lds_cache_dir: /home/yolcu/DualView_wip/cache/MNIST/corrupt
metric: corrupt
model_name: basic_conv
model_path: /home/yolcu/DualView_wip/checkpoints/MNIST/corrupt/MNIST_basic_conv_best
num_classes: 10
save_dir: /home/yolcu/DualView_wip/test_output/representer_0.1
validation_size: 2000
xai_method: representer
xpl_root: /home/yolcu/DualView_wip/explanations/MNIST/std/representer_0.1/
