C: '0.001'
accuracy: true
batch_size: 32
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: C:/Users/weckbecker/DualView-wip/src/datasets
dataset_name: CIFAR
dataset_type: std
device: cuda
model_name: resnet
model_path: C:/Users/weckbecker/DualView-wip/checkpoints/CIFAR/std/resnet_std/CIFAR_resnet
num_batches_per_file: 100
num_classes: 10
num_files: 500
save_dir_explainer: C:/Users/weckbecker/DualView-wip/explanations/CIFAR/std/resnet_std/dualview_model_labels_0.001
save_dir_results: C:/Users/weckbecker/DualView-wip/surrogate_check/CIFAR/std/resnet_std/dualview_model_labels_0.001
start_file: 0
validation_size: 2000
xai_method: dualview
