C: '0.00001'
accuracy: true
batch_size: 32
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: C:/Users/weckbecker/DualView-wip/src/datasets
dataset_name: CIFAR
dataset_type: group
device: cuda
model_name: resnet
model_path: C:/Users/weckbecker/DualView-wip/checkpoints/CIFAR/group/resnet_group/CIFAR_resnet
num_batches_per_file: 100
num_classes: 5
num_files: 500
save_dir_explainer: C:/Users/weckbecker/DualView-wip/explanations/CIFAR/group/resnet_group/dualview_0.00001
save_dir_results: C:/Users/weckbecker/DualView-wip/surrogate_check/CIFAR/group/resnet_group/dualview_0.00001
start_file: 0
validation_size: 2000
xai_method: dualview
