augmentation: crop_flip
batch_size: 16
cache_dir: /mnt/outputs/CIFAR/lds
data_root: /mnt/dataset
dataset_name: CIFAR
dataset_type: std
device: cuda
epochs: 190
loss: cross_entropy
lr: 0.001
metric: lds_cache
model_name: resnet18
momentum: 0.9
num_classes: 10
optimizer: sgd
sample_nr: 68
save_dir: /mnt/outputs/
scheduler: constant
validation_size: 2000
weight_decay: 0.01
