C: 1.0e-05
augmentation: crop_flip
batch_size: 8
cache_dir: /home/yolcu/Documents/Code/DualXDA/cache/CIFAR/std/dualda_1e_05
data_root: <data_root>
dataset_name: CIFAR
dataset_type: std
device: cpu
epochs: 190
features_dir: /home/yolcu/Documents/Code/DualXDA/cache/CIFAR/std/features
grad_dir: /home/yolcu/Documents/Code/DualXDA/cache/CIFAR/std/tracin/best
lds_cache_dir: /home/yolcu/Documents/Code/DualXDA/cache/CIFAR/lds
loss: cross_entropy
lr: 0.0003333333333333333
metric: lds
model_name: resnet18
model_path: /home/yolcu/Documents/Code/DualXDA/checkpoints/CIFAR/std/CIFAR_resnet18_best
momentum: 0.9
num_classes: 10
optimizer: sgd
save_dir: /home/yolcu/Documents/Code/DualXDA/test_output
scheduler: constant
validation_size: 2000
weight_decay: 0.01
xai_method: dualda
xpl_root: /home/yolcu/Documents/Code/DualXDA/explanations/CIFAR/std/dualda_1e_05/
