C: 1.0e-05
batch_size: 32
cache_dir: /home/yolcu/Documents/Code/DualXDA/cache/CIFAR/mark/dualda_1e_05
data_root: <data_root>
dataset_name: CIFAR
dataset_type: mark
device: cpu
features_dir: /home/yolcu/Documents/Code/DualXDA/cache/CIFAR/mark/features
grad_dir: /home/yolcu/Documents/Code/DualXDA/cache/CIFAR/mark/tracin/best
lds_cache_dir: /home/yolcu/Documents/Code/DualXDA/cache/CIFAR/shortcut_detection
metric: shortcut_detection
model_name: resnet18
model_path: /home/yolcu/Documents/Code/DualXDA/checkpoints/CIFAR/mark/CIFAR_resnet18_best
num_classes: 10
save_dir: /home/yolcu/Documents/Code/DualXDA/test_output
validation_size: 2000
xai_method: dualda
xpl_root: /home/yolcu/Documents/Code/DualXDA/explanations/CIFAR/mark/dualda_1e_05/
