C: 0.1
batch_size: 32
cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/corrupt/dualview_0.1
data_root: <data_root>
dataset_name: CIFAR
dataset_type: corrupt
device: cpu
features_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/corrupt/features
grad_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/corrupt/tracin/best
lds_cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/mislabeling_detection
metric: mislabeling_detection
model_name: resnet18
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/CIFAR/corrupt/CIFAR_resnet18_best
num_classes: 10
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/test_output
validation_size: 2000
xai_method: dualview
xpl_root: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/CIFAR/corrupt/dualview_0.1/
