C: 1.0e-05
batch_size: 32
cache_dir: /home/yolcu/Documents/Code/DualXDA/cache/CIFAR/group/dualda_1e_05
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: <data_root>
dataset_name: CIFAR
dataset_type: group
device: cpu
features_dir: /home/yolcu/Documents/Code/DualXDA/cache/CIFAR/group/features
grad_dir: /home/yolcu/Documents/Code/DualXDA/cache/CIFAR/group/tracin/best
lds_cache_dir: /home/yolcu/Documents/Code/DualXDA/cache/CIFAR/subclass_detection
metric: subclass_detection
model_name: resnet18
model_path: /home/yolcu/Documents/Code/DualXDA/checkpoints/CIFAR/group/CIFAR_resnet18_best
num_classes: 10
save_dir: /home/yolcu/Documents/Code/DualXDA/test_output
validation_size: 2000
xai_method: dualda
xpl_root: /home/yolcu/Documents/Code/DualXDA/explanations/CIFAR/group/dualda_1e_05/
