C: 0.001
batch_size: 32
cache_dir: /home/yolcu/Documents/Code/DualXDA/cache/CIFAR/std/dualda_0.001
data_root: <data_root>
dataset_name: CIFAR
dataset_type: std
device: cpu
features_dir: /home/yolcu/Documents/Code/DualXDA/cache/CIFAR/std/features
grad_dir: /home/yolcu/Documents/Code/DualXDA/cache/CIFAR/std/tracin/best
lds_cache_dir: /home/yolcu/Documents/Code/DualXDA/cache/CIFAR/class_detection
metric: class_detection
model_name: resnet18
model_path: /home/yolcu/Documents/Code/DualXDA/checkpoints/CIFAR/std/CIFAR_resnet18_best
num_classes: 10
save_dir: /home/yolcu/Documents/Code/DualXDA/test_output
validation_size: 2000
xai_method: dualda
xpl_root: /home/yolcu/Documents/Code/DualXDA/explanations/CIFAR/std/dualda_0.001/
