C: 1.0e-05
batch_size: 32
cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/mark/dualview_1e_05
data_root: <data_root>
dataset_name: CIFAR
dataset_type: mark
device: cpu
features_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/mark/features
grad_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/mark/tracin/best
lds_cache_dir: /home/fe/yolcu/Documents/Code/DualView-wip/cache/CIFAR/shortcut_detection
metric: shortcut_detection
model_name: resnet18
model_path: /home/fe/yolcu/Documents/Code/DualView-wip/checkpoints/CIFAR/mark/CIFAR_resnet18_best
num_classes: 10
save_dir: /home/fe/yolcu/Documents/Code/DualView-wip/test_output
validation_size: 2000
xai_method: dualview
xpl_root: /home/fe/yolcu/Documents/Code/DualView-wip/explanations/CIFAR/mark/dualview_1e_05/
