augmentation: crop_flip
batch_size: 16
cache_dir: /home/yolcu/Documents/Code/DualXDA/cache/CIFAR/lds
data_root: <data_root>
dataset_name: CIFAR
dataset_type: std
device: cpu
epochs: 190
loss: cross_entropy
lr: 0.001
metric: lds_cache
model_name: resnet18
momentum: 0.9
num_classes: 10
optimizer: sgd
sample_nr: 67
save_dir: /home/yolcu/Documents/Code/DualXDA/cache/CIFAR/lds
scheduler: constant
validation_size: 2000
weight_decay: 0.01
