C: 0.1
batch_size: 16
data_root: /mnt/dataset
dataset_name: AWA
device: cuda
metric: mark
model_name: resnet50
num_classes: 50
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: dualview
xpl_root: mnt/explanations/AWA/mark/resnet50_mark/dualview_0.1
