C: 0.001
augmentation: flip
batch_size: 16
cache_dir: /mnt/cache/AWA/std/dualview_0.001
data_root: /mnt/dataset
dataset_name: AWA
dataset_type: std
device: cuda
epochs: 30
features_dir: /mnt/cache/AWA/std/features
grad_dir: /mnt/cache/AWA/std/tracin/best
loss: cross_entropy
lr: 0.0033333333333333335
metric: labelflip
model_name: resnet50
momentum: 0.9
num_classes: 50
optimizer: sgd
save_dir: /mnt/outputs/
scheduler: annealing
validation_size: 2000
weight_decay: 0
xai_method: dualview
xpl_root: /mnt/explanations/AWA/std/dualview/
