C: 0.01
augmentation: flip
batch_size: 8
cache_dir: /mnt/cache/AWA/std/dualview_0.01
data_root: /mnt/dataset
dataset_name: AWA
dataset_type: std
device: cuda
epochs: 30
features_dir: /mnt/cache/AWA/std/features
grad_dir: /mnt/cache/AWA/std/tracin/best
loss: cross_entropy
lr: 0.0033333333333333335
metric: leave_out
model_name: resnet50
model_path: /mnt/checkpoints/AWA/std/resnet50_leave_out/AWA_resnet50
momentum: 0.9
num_classes: 50
optimizer: sgd
save_dir: /mnt/outputs/
scheduler: annealing
validation_size: 2000
weight_decay: 0
xai_method: dualview
xpl_root: /mnt/explanations/AWA/std/dualview/
