augmentation: flip
batch_size: 8
cache_dir: /mnt/cache/AWA/std/input_similarity_dot
data_root: /mnt/dataset
dataset_name: AWA
dataset_type: std
device: cuda
epochs: 30
features_dir: /mnt/cache/AWA/std/features
grad_dir: /mnt/cache/AWA/std/tracin/best
lds_cache_dir: /mnt/cache/AWA/only_batch
loss: cross_entropy
lr: 0.001
metric: only_batch
model_name: resnet50
model_path: /mnt/checkpoints/AWA/std/AWA_resnet50_best
momentum: 0.9
num_classes: 50
optimizer: sgd
save_dir: /mnt/outputs/
scheduler: constant
validation_size: 2000
weight_decay: 0
xai_method: input_similarity_dot
xpl_root: /mnt/explanations/AWA/std/input_similarity_dot/
