C: 1
batch_size: 16
cache_dir: /mnt/cache/AWA/mark/dualview_1
data_root: /mnt/dataset
dataset_name: AWA
dataset_type: mark
device: cuda
features_dir: /mnt/cache/AWA/mark/features
grad_dir: /mnt/cache/AWA/mark/tracin/best
metric: mark
model_name: resnet50
model_path: /mnt/checkpoints/AWA/mark/resnet50_mark/AWA_resnet50
num_classes: 50
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: dualview
xpl_root: /mnt/explanations/AWA/mark/dualview/
