C: 0.01
augmentation: flip
batch_size: 16
data_root: /mnt/dataset
dataset_name: AWA
dataset_type: std
device: cuda
epochs: 50
loss: cross_entropy
lr: 0.01
metric: only_batch
model_name: resnet50
momentum: 0.9
num_classes: 50
optimizer: sgd
save_dir: /mnt/outputs/
scheduler: annealing
validation_size: 2000
weight_decay: 0
xai_method: dualview
xpl_root: /mnt/xpl/AWA/std/dualview/
