C: 1.0e-05
batch_size: 128
cache_dir: /mnt/cache/AWA/corrupt/representer
data_root: /mnt/dataset
dataset_name: AWA
dataset_type: corrupt
device: cuda
features_dir: /mnt/cache/AWA/corrupt/features
grad_dir: /mnt/cache/AWA/corrupt/tracin/best
lds_cache_dir: /mnt/cache/AWA/corrupt
metric: corrupt
model_name: resnet50
model_path: /mnt/checkpoints/AWA/corrupt/AWA_resnet50_best
num_classes: 50
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: representer
xpl_root: /mnt/explanations/AWA/std/representer_1e-05/
