batch_size: 16
data_root: /mnt/dataset
dataset_name: AWA
device: cuda
metric: mark
model_name: resnet50
num_classes: 50
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: influence
xpl_root: /mnt/explanations/AWA/mark/resnet50_mark/influence
