batch_size: 16
cache_dir: /mnt/cache/AWA/mark/input_similarity_dot
data_root: /mnt/dataset
dataset_name: AWA
dataset_type: mark
device: cuda
features_dir: /mnt/cache/AWA/mark/features
grad_dir: /mnt/cache/AWA/mark/tracin/best
lds_cache_dir: /mnt/cache/AWA/lds
metric: mark
model_name: resnet50
model_path: /mnt/checkpoints/AWA/mark/AWA_resnet50_best
num_classes: 50
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: input_similarity_dot
xpl_root: /mnt/explanations/AWA/mark/input_similarity_dot/
