batch_size: 16
data_root: /mnt/dataset
dataset_name: AWA
dataset_type: switched
device: cuda
metric: switched
model_name: resnet50
num_classes: 50
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: tracin
xpl_root: /mnt/xpl/AWA/switched_one_file/tracin/
