batch_size: 16
cache_dir: /mnt/cache/AWA/std/tracin
data_root: /mnt/dataset
dataset_name: AWA
dataset_type: std
device: cuda
features_dir: /mnt/cache/AWA/std/features
grad_dir: /mnt/cache/AWA/std/tracin/best
metric: stdk
model_name: resnet50
model_path: /mnt/checkpoints/AWA/std/resnet50_stdk/AWA_resnet50
num_classes: 50
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: graddot
xpl_root: /mnt/explanations/AWA/std/graddot/
