batch_size: 128
data_root: /mnt/dataset
dataset_name: AWA
dataset_type: std
device: cuda
metric: stdk
model_name: resnet50
num_classes: 50
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: representer
xpl_root: /mnt/xpl/AWA/std/representer/
