C: 0.001
batch_size: 16
cache_dir: /mnt/cache/AWA/std/dualview_0.001
data_root: /mnt/dataset
dataset_name: AWA
dataset_type: std
device: cuda
features_dir: /mnt/cache/AWA/std/features
grad_dir: /mnt/cache/AWA/std/tracin/best
metric: stdk
model_name: resnet50
model_path: /mnt/checkpoints/AWA/std/AWA_resnet50_best
num_classes: 50
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: dualview
xpl_root: /mnt/explanations/AWA/std/dualview_0.001/
