batch_size: 16
cache_dir: /mnt/cache/AWA/std/arnoldi
data_root: /mnt/dataset
dataset_name: AWA
dataset_type: std
device: cuda
features_dir: /mnt/cache/AWA/std/features
grad_dir: /mnt/cache/AWA/std/tracin/best
metric: std
model_name: resnet50
num_classes: 50
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: arnoldi
xpl_root: /mnt/explanations/AWA/std/arnoldi/
