batch_size: 16
cache_dir: /mnt/cache/AWA/corrupt/input_similarity_cos
data_root: /mnt/dataset
dataset_name: AWA
dataset_type: corrupt
device: cuda
features_dir: /mnt/cache/AWA/corrupt/features
grad_dir: /mnt/cache/AWA/corrupt/tracin/best
lds_cache_dir: /mnt/cache/AWA/lds
metric: corrupt
model_name: resnet50
model_path: /mnt/checkpoints/AWA/corrupt/AWA_resnet50_best
num_classes: 50
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: input_similarity_cos
xpl_root: /mnt/explanations/AWA/std/input_similarity_cos/
