C: 0.1
batch_size: 16
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: /mnt/dataset
dataset_name: AWA
device: cuda
metric: std
model_name: resnet50
num_classes: 50
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: rp_similarity
xpl_root: mnt/explanations/AWA/std/resnet50_std/rp_similarity
