C: 0.1
augmentation: flip
batch_size: 16
data_root: /mnt/dataset
dataset_name: AWA
device: cuda
epochs: 100
loss: cross_entropy
lr: 0.01
metric: add_batch_in_neg
model_name: resnet50
momentum: 0
num_classes: 50
optimizer: sgd
save_dir: /mnt/outputs/
scheduler: constant
validation_size: 2000
weight_decay: 0
xai_method: dualview
xpl_root: /mnt/explanations/AWA/std/resnet50_std/dualview_0.1
