C: 0.01
batch_size: 16
cache_dir: /mnt/cache/AWA/corrupt/dualview_0.01
data_root: /mnt/dataset
dataset_name: AWA
dataset_type: corrupt
device: cuda
features_dir: /mnt/cache/AWA/corrupt/features
grad_dir: /mnt/cache/AWA/corrupt/tracin/best
metric: corrupt
model_name: resnet50
model_path: /mnt/checkpoints/AWA/corrupt/resnet50_corrupt/AWA_resnet50
num_classes: 50
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: dualview
xpl_root: /mnt/explanations/AWA/std/dualview/
