C: 1.0e-05
batch_size: 128
cache_dir: /mnt/cache/AWA/mark/representer
data_root: /mnt/dataset
dataset_name: AWA
dataset_type: mark
device: cuda
features_dir: /mnt/cache/AWA/mark/features
grad_dir: /mnt/cache/AWA/mark/tracin/best
lds_cache_dir: /mnt/cache/AWA/mark
metric: mark
model_name: resnet50
model_path: /mnt/checkpoints/AWA/mark/AWA_resnet50_best
num_classes: 50
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: representer
xpl_root: /mnt/explanations/AWA/mark/representer_1e-05/
