batch_size: 16
data_root: /mnt/dataset
dataset_name: AWA
device: cuda
metric: switched
model_name: resnet50
num_classes: 50
save_dir: /mnt/outputs/
validation_size: 2000
xai_method: influence
xpl_root: mnt/explanations/AWA/switched_one_file/resnet50_switched_one_file/influence
