C: 1.0e-05
augmentation: flip
batch_size: 8
cache_dir: /mnt/cache/AWA/std/representer
data_root: /mnt/dataset
dataset_name: AWA
dataset_type: std
device: cuda
epochs: 30
features_dir: /mnt/cache/AWA/std/features
grad_dir: /mnt/cache/AWA/std/tracin/best
lds_cache_dir: /mnt/cache/AWA/add_batch_in_neg
loss: cross_entropy
lr: 0.001
metric: add_batch_in_neg
model_name: resnet50
model_path: /mnt/checkpoints/AWA/std/AWA_resnet50_best
momentum: 0.9
num_classes: 50
optimizer: sgd
save_dir: /mnt/outputs/
scheduler: constant
validation_size: 2000
weight_decay: 0
xai_method: representer
xpl_root: /mnt/explanations/AWA/std/representer_1e-05/
