C: 0.001
batch_size: 128
cache_dir: /home/yolcu/DualView_wip/cache/AWA/std/representer
data_root: /media/yolcu/
dataset_name: AWA
dataset_type: std
device: cuda
features_dir: /home/yolcu/DualView_wip/cache/AWA/std/features
grad_dir: /home/yolcu/DualView_wip/cache/AWA/std/tracin/best
lds_cache_dir: /home/yolcu/DualView_wip/cache/AWA/stdk
metric: stdk
model_name: resnet50
model_path: /home/yolcu/DualView_wip/checkpoints/AWA/std/AWA_resnet50_best
num_classes: 50
save_dir: /home/yolcu/DualView_wip/test_output/representer_0.001
validation_size: 2000
xai_method: representer
xpl_root: /home/yolcu/DualView_wip/explanations/AWA/std/representer_0.001/
