C: 1.0e-05
batch_size: 128
cache_dir: /home/yolcu/DualView_wip/cache/AWA/mark/representer
data_root: /media/yolcu/
dataset_name: AWA
dataset_type: mark
device: cuda
features_dir: /home/yolcu/DualView_wip/cache/AWA/mark/features
grad_dir: /home/yolcu/DualView_wip/cache/AWA/mark/tracin/best
lds_cache_dir: /home/yolcu/DualView_wip/cache/AWA/mark
metric: mark
model_name: resnet50
model_path: /home/yolcu/DualView_wip/checkpoints/AWA/mark/AWA_resnet50_best
num_classes: 50
save_dir: /home/yolcu/DualView_wip/test_output/representer_1e-05
validation_size: 2000
xai_method: representer
xpl_root: /home/yolcu/DualView_wip/explanations/AWA/mark/representer_1e-05/
