C: 0.1
batch_size: 128
cache_dir: /home/yolcu/DualView_wip/cache/AWA/corrupt/representer
data_root: /media/yolcu/
dataset_name: AWA
dataset_type: corrupt
device: cuda
features_dir: /home/yolcu/DualView_wip/cache/AWA/corrupt/features
grad_dir: /home/yolcu/DualView_wip/cache/AWA/corrupt/tracin/best
lds_cache_dir: /home/yolcu/DualView_wip/cache/AWA/corrupt
metric: corrupt
model_name: resnet50
model_path: /home/yolcu/DualView_wip/checkpoints/AWA/corrupt/AWA_resnet50_best
num_classes: 50
save_dir: /home/yolcu/DualView_wip/test_output/representer_0.1
validation_size: 2000
xai_method: representer
xpl_root: /home/yolcu/DualView_wip/explanations/AWA/std/representer_0.1/
