C: 0.001
augmentation: flip
batch_size: 8
cache_dir: /home/yolcu/DualView_wip/cache/AWA/std/representer
data_root: /media/yolcu/
dataset_name: AWA
dataset_type: std
device: cuda
epochs: 30
features_dir: /home/yolcu/DualView_wip/cache/AWA/std/features
grad_dir: /home/yolcu/DualView_wip/cache/AWA/std/tracin/best
lds_cache_dir: /home/yolcu/DualView_wip/cache/AWA/add_batch_in_neg
loss: cross_entropy
lr: 0.001
metric: add_batch_in_neg
model_name: resnet50
model_path: /home/yolcu/DualView_wip/checkpoints/AWA/std/AWA_resnet50_best
momentum: 0.9
num_classes: 50
optimizer: sgd
save_dir: /home/yolcu/DualView_wip/test_output/representer_0.001
scheduler: constant
validation_size: 2000
weight_decay: 0
xai_method: representer
xpl_root: /home/yolcu/DualView_wip/explanations/AWA/std/representer_0.001/
