C: 1.0e-05
accuracy: true
batch_size: 200
cache_dir: /mnt/cache/CIFAR/switched/dualview_1e-05
data_root: /mnt/dataset/
dataset_name: CIFAR
dataset_type: switched
device: cuda
features_dir: /mnt/cache/CIFAR/switched/features
grad_dir: /mnt/cache/CIFAR/switched/tracin/best
model_name: resnet18
model_path: /mnt/checkpoints/CIFAR/switched/CIFAR_resnet18
num_batches_per_file: 1
num_classes: 10
num_files: 1
save_dir: /mnt/outputs/
start_file: 5
validation_size: 2000
xai_method: dualview
