accuracy: true
batch_size: 20
data_root: /mnt/dataset/
dataset_name: CIFAR
dataset_type: corrupt
device: cuda
model_name: resnet18
model_path: /mnt/checkpoints/CIFAR/corrupt/CIFAR_resnet18_189
num_batches_per_file: 1
num_classes: 10
num_files: 1
save_dir: /mnt/outputs/
start_file: 17
validation_size: 2000
xai_method: trak
