C: 0.91
accuracy: true
batch_size: 20
cache_dir: /mnt/cache/CIFAR/group/representer_0.91
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: /mnt/dataset/
dataset_name: CIFAR
dataset_type: group
device: cuda
features_dir: /mnt/cache/CIFAR/group/features
grad_dir: /mnt/cache/CIFAR/group/tracin/best
model_name: resnet18
model_path: /mnt/checkpoints/CIFAR/group/CIFAR_resnet18_best
num_batches_per_file: 1
num_classes: 10
num_files: 1
save_dir: /mnt/outputs/
start_file: 33
validation_size: 2000
xai_method: representer
