C: 0.98
accuracy: true
batch_size: 20
cache_dir: /mnt/cache/CIFAR/std/representer_0.98
data_root: /mnt/dataset/
dataset_name: CIFAR
dataset_type: std
device: cuda
features_dir: /mnt/cache/CIFAR/std/features
grad_dir: /mnt/cache/CIFAR/std/tracin/best
model_name: resnet18
model_path: /mnt/checkpoints/CIFAR/std/CIFAR_resnet18_best
num_batches_per_file: 1
num_classes: 10
num_files: 1
save_dir: /mnt/outputs/
start_file: 93
validation_size: 2000
xai_method: representer
