C: 0.1
accuracy: true
batch_size: 128
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: /mnt/dataset/
dataset_name: CIFAR
dataset_type: switched_one_file
device: cuda
model_name: resnet18
model_path: /mnt/checkpoints/CIFAR/switched_one_file/resnet18_switched_one_file/CIFAR_resnet18
num_batches_per_file: 1
num_classes: 10
num_files: 100
save_dir: /mnt/outputs/
skip: 2230
start_file: 0
validation_size: 2000
xai_method: representer
