C: 0.1
accuracy: true
batch_size: 16
data_root: /mnt/dataset/
dataset_name: CIFAR
dataset_type: std
device: cuda
model_name: resnet18
model_path: /mnt/checkpoints/CIFAR/std/resnet18_std/CIFAR_resnet18
num_batches_per_file: 1
num_classes: 10
num_files: 100
save_dir: /mnt/outputs/
skip: 2230
start_file: 0
validation_size: 2000
xai_method: dualview
