C: 0.001
batch_size: 128
cache_dir: /home/yolcu/DualView_wip/cache/CIFAR/group/representer
class_groups:
- - 0
  - 1
- - 2
  - 3
- - 4
  - 5
- - 6
  - 7
- - 8
  - 9
data_root: /media/yolcu/
dataset_name: CIFAR
dataset_type: group
device: cuda
features_dir: /home/yolcu/DualView_wip/cache/CIFAR/group/features
grad_dir: /home/yolcu/DualView_wip/cache/CIFAR/group/tracin/best
lds_cache_dir: /home/yolcu/DualView_wip/cache/CIFAR/groupk
metric: groupk
model_name: resnet18
model_path: /home/yolcu/DualView_wip/checkpoints/CIFAR/group/CIFAR_resnet18_best
num_classes: 10
save_dir: /home/yolcu/DualView_wip/test_output/representer_0.001
validation_size: 2000
xai_method: representer
xpl_root: /home/yolcu/DualView_wip/explanations/CIFAR/group/representer_0.001/
