C: 0.1
batch_size: 128
cache_dir: /home/yolcu/DualView_wip/cache/CIFAR/corrupt/representer
data_root: /media/yolcu/
dataset_name: CIFAR
dataset_type: corrupt
device: cuda
features_dir: /home/yolcu/DualView_wip/cache/CIFAR/corrupt/features
grad_dir: /home/yolcu/DualView_wip/cache/CIFAR/corrupt/tracin/best
lds_cache_dir: /home/yolcu/DualView_wip/cache/CIFAR/corrupt
metric: corrupt
model_name: resnet18
model_path: /home/yolcu/DualView_wip/checkpoints/CIFAR/corrupt/CIFAR_resnet18_best
num_classes: 10
save_dir: /home/yolcu/DualView_wip/test_output/representer_0.1
validation_size: 2000
xai_method: representer
xpl_root: /home/yolcu/DualView_wip/explanations/CIFAR/std/representer_0.1/
