C: 0.1
batch_size: 128
cache_dir: /home/yolcu/DualView_wip/cache/CIFAR/mark/representer
data_root: /media/yolcu/
dataset_name: CIFAR
dataset_type: mark
device: cuda
features_dir: /home/yolcu/DualView_wip/cache/CIFAR/mark/features
grad_dir: /home/yolcu/DualView_wip/cache/CIFAR/mark/tracin/best
lds_cache_dir: /home/yolcu/DualView_wip/cache/CIFAR/mark
metric: mark
model_name: resnet18
model_path: /home/yolcu/DualView_wip/checkpoints/CIFAR/mark/CIFAR_resnet18_best
num_classes: 10
save_dir: /home/yolcu/DualView_wip/test_output/representer_0.1
validation_size: 2000
xai_method: representer
xpl_root: /home/yolcu/DualView_wip/explanations/CIFAR/mark/representer_0.1/
