C: 0.001
augmentation: crop_flip
batch_size: 8
cache_dir: /home/yolcu/DualView_wip/cache/CIFAR/std/representer
data_root: /media/yolcu/
dataset_name: CIFAR
dataset_type: std
device: cuda
epochs: 190
features_dir: /home/yolcu/DualView_wip/cache/CIFAR/std/features
grad_dir: /home/yolcu/DualView_wip/cache/CIFAR/std/tracin/best
lds_cache_dir: /home/yolcu/DualView_wip/cache/CIFAR/add_batch_in_neg
loss: cross_entropy
lr: 0.0003333333333333333
metric: add_batch_in_neg
model_name: resnet18
model_path: /home/yolcu/DualView_wip/checkpoints/CIFAR/std/CIFAR_resnet18_best
momentum: 0.9
num_classes: 10
optimizer: sgd
save_dir: /home/yolcu/DualView_wip/test_output/representer_0.001
scheduler: constant
validation_size: 2000
weight_decay: 0.01
xai_method: representer
xpl_root: /home/yolcu/DualView_wip/explanations/CIFAR/std/representer_0.001/
