C: 1.0e-05
batch_size: 128
cache_dir: /home/yolcu/DualView_wip/cache/CIFAR/std/representer
data_root: /media/yolcu/
dataset_name: CIFAR
dataset_type: std
device: cuda
features_dir: /home/yolcu/DualView_wip/cache/CIFAR/std/features
grad_dir: /home/yolcu/DualView_wip/cache/CIFAR/std/tracin/best
lds_cache_dir: /home/yolcu/DualView_wip/cache/CIFAR/stdk
metric: stdk
model_name: resnet18
model_path: /home/yolcu/DualView_wip/checkpoints/CIFAR/std/CIFAR_resnet18_best
num_classes: 10
save_dir: /home/yolcu/DualView_wip/test_output/representer_1e-05
validation_size: 2000
xai_method: representer
xpl_root: /home/yolcu/DualView_wip/explanations/CIFAR/std/representer_1e-05/
